### ISSUE TITLE
Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/ipex-llm#10262]
when I run chatglm example on xpu, I met an issue is like below, have you please ever met that? thanks a lot
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
:: WARNING: setvars.bat has already been run. Skipping re-execution.
   To force a re-execution of setvars.bat, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.
C:\ProgramData\anaconda3\envs\llmsd_env\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-02-27 05:38:54,932 - root - INFO - intel_extension_for_pytorch auto imported
2024-02-27 05:38:55,058 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......

**Comment by Oscilloscope98** [comment]
Hi @aoke79 ,

This is just an warning thrown by ipex. You could ignore it if you are just running our ChatGLM examples on XPU, or as the warning mentioned, if you don't plan on using image functionality from torchvision.io.

Please let us know for any further problem :)

**Comment by aoke79** [comment]
thanks a lot for your quick response, I just think it's a little boring. :)

**Comment by Edward-Lin** [comment]
please help close it. thanks
