### ISSUE TITLE
New instructions about "Run Distributed QLoRA Fine-Tuning on Kubernetes" in MPI-Operator v1alpha1 and  with kubectl method

### ISSUE THREAD

**Issue by antchainmappic** [intel-analytics/ipex-llm#10304]
Please provide new instructions about how to run distributed QLoRA Fine-Tuning on Kubernetes in MPI-Operator v1alpha1 version and with kubectl method in "Run Distributed QLoRA Fine-Tuning on Kubernetes" chapter, thanks.

**Comment by glorysdj** [comment]
please refer to this:
https://github.com/intel-analytics/BigDL/blob/main/docker/llm/finetune/qlora/cpu/kubernetes/README.md
