### ISSUE TITLE
Failed to run Llama 2 inference on Flex 140

### ISSUE THREAD

**Issue by HLneoh** [intel-analytics/ipex-llm#10331]
Hi, below screenshot captured the error encountered while running this sample, https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/PyTorch-Models/Model/llama2/generate.py

Command used:
python ./generate.py --repo-id-or-model-path meta-llama/Llama-2-7b-chat-hf

![image](https://github.com/intel-analytics/BigDL/assets/25906607/ae5c5946-114a-48ba-b067-ccc26f5640fb)

My system environment:
[env_info.txt](https://github.com/intel-analytics/BigDL/files/14497744/env_info.txt)

**Comment by qiuxin2012** [comment]
This error is caused by out of GPU memory. See our faq https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/FAQ/faq.html#native-api-failed-native-api-returns-5-pi-error-out-of-resources-5-pi-error-out-of-resources
Could you check your Memory Physical Size(output of `sudo xpu-smi discovery -d 0`)? See https://dgpu-docs.intel.com/driver/installation.html#xpu-smi-device-information-and-telemetry. We just find one of customer's Flex 140 only has 5GB memory, but it should be 12GB.

**Comment by HLneoh** [comment]
Hi @qiuxin2012, my GPU only has 5GB.

![image](https://github.com/intel-analytics/BigDL/assets/25906607/59e65a16-5c1a-4f5a-8e37-09628b56e3c8)

**Comment by HLneoh** [comment]
Hi @rnwang04, from what I understand, the flex 140 has two GPUs per card, with a memory capacity of 12GB (6GB per GPU). See attached for my output of `sudo xpu-smi discovery -d 0`. 

![image](https://github.com/intel-analytics/BigDL/assets/25906607/7bbfdcee-8134-43f2-80b6-29352884d596)
![image](https://github.com/intel-analytics/BigDL/assets/25906607/1f9a4bdb-22f8-4e01-9fef-fd10d5a7db6b)

**Comment by jason-dai** [comment]
In this case, we many need to run the model inference on two cards using TP or PP.

**Comment by rnwang04** [comment]
As flex 140's memory is so limited, you may add `cpu_embedding=True` in https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/llama2/generate.py to help save memory of Embedding layer and see whether it works :

```python
    model = AutoModelForCausalLM.from_pretrained(model_path,
                                                 load_in_4bit=True,
                                                 optimize_model=True,
                                                 trust_remote_code=True,
                                                 use_cache=True,
                                                 cpu_embedding=True)
```

If not, you can try to run the model inference on two cards using TP or PP, related example is here: https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/Deepspeed-AutoTP
