### ISSUE TITLE
The progress of fine-tuning Aliyun Kubernetes using BigDL distributed QLoRA is slow.

### ISSUE THREAD

**Issue by antchainmappic** [intel-analytics/ipex-llm#10388]
Hi，I'm using Kubernetes to fine-tuning LLM In TDX environment followed by this instruction：https://github.com/intel-analytics/BigDL/blob/main/docker/llm/finetune/qlora/cpu/kubernetes/README.md

But the process is going very slow(about to take 20+ hours), according to my hardware, this shouldn't be that slow, could you help us to solve this problem?

![image](https://github.com/intel-analytics/BigDL/assets/143392965/44ca89a2-c3f2-4a7c-9bc6-d4f5fe9ed83f)

![image](https://github.com/intel-analytics/BigDL/assets/143392965/58670d58-40ba-40f1-9dee-a13391c8c687)

Here are my hardware and some training ENV informations:

  Aliyun  ECS 32C128G *3

![image](https://github.com/intel-analytics/BigDL/assets/143392965/408643cc-20cb-401c-bc7d-59cb78583ab7)

**Comment by Uxito-Ada** [comment]
According to my experience, 23h is modest for 3*32 cores, for 3 epochs on alpaca dataset.
Do you have a 1 instance baseline on your platform?

**Comment by Uxito-Ada** [comment]
WIP to analyze and solve it.
