### ISSUE TITLE
Qwen-7b-chat inference with W1A16 is faster than W1A32, why don't use "model = model.half()" as defaut?

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10415]
numactl -C 0-6 python generate.py --repo-id-or-model-path /home/intel/LLM/Qwen-7B-Chat/ --n-predict 512 --prompt "折纸的过程看似简单，其实想要做好，还是需要一套很复杂的工艺。以折一支玫瑰花为例，我们可以将整个折纸过程分成三个阶段，即：创建栅格折痕，制作立 体基座，完成花瓣修饰。首先是创建栅格折痕：这一步有点像我们折千纸鹤的第一步，即通过对称州依次对折，然后按照长和宽两个维度，依次进行多等分的均匀折叠；最终在两个方向上的折痕会交织成一套 完整均匀的小方格拼接图案；这些小方格就组成了类似二维坐标系的参考系统，使得我们在该平面上，通过组合临近折痕的方式从二维小方格上折叠出三维的高台或凹陷，以便于接下来的几座制作过程。需要 注意的是，在建立栅格折痕的过程中，可能会出现折叠不对成的情况，这种错误所带来的后果可能是很严重的，就像是蝴蝶效应，一开始只是毫厘之差，最后可能就是天壤之别。然后是制作立体基座：在这一 步，我们需要基于栅格折痕折出对称的三维高台或凹陷。从对称性分析不难发现，玫瑰花会有四个周对称的三维高台和配套凹陷。所以，我们可以先折出四分之一的凹陷和高台图案，然后以这四分之一的部分 作为摸板，再依次折出其余三个部分的重复图案。值得注意的是，高台的布局不仅要考虑长和宽这两个唯独上的规整衬度和对称分布，还需要同时保证高这个维度上的整齐。与第一阶段的注意事项类似，请处 理好三个维度上的所有折角，确保它们符合计划中所要求的那种布局，以免出现三维折叠过程中的蝴蝶效应；为此，我们常常会在折叠第一个四分之一图案的过程中，与成品玫瑰花进行反复比较，以便在第一 时间排除掉所有可能的错误。最后一个阶段是完成花瓣修饰。在这个阶段，我们往往强调一个重要名词，叫用心折叠。这里的用心已经不是字面上的认真这个意思，而是指通过我们对于大自然中玫瑰花外型的 理解，借助自然的曲线去不断修正花瓣的形状，以期逼近现实中的玫瑰花瓣外形。请注意，在这个阶段的最后一步，我们需要通过拉扯已经弯折的四个花瓣，来调整玫瑰花中心的绽放程度。这个过程可能会伴 随玫瑰花整体结构的崩塌，所以，一定要控制好调整的力道，以免出现不可逆的后果。最终，经过三个阶段的折叠，我们会得到一支栩栩如生的玫瑰花冠。如果条件允许，我们可以在一根拉直的铁丝上缠绕绿 色纸条，并将玫瑰花冠插在铁丝的一段。这样，我们就得到了一支手工玫瑰花。总之，通过创建栅格折痕，制作立体基座，以及完成花瓣修饰，我们从二维的纸面上创作出了一支三维的花朵。这个过程虽然看 似简单，但它确实我们人类借助想象力和常见素材而创作出的艺术品。问: 请基于以上描述，分析哪些步骤做错了很大可能会导致最终折叠失败？"

-----------------------W4A16-------------------------------------------------------
<class 'transformers_modules.modeling_qwen.QWenLMHeadModel'>
=========First token cost 3.0140 s and 8.162109375 GB=========
=========Rest tokens cost average 0.0305 s (177 tokens in all) and 8.169921875 GB=========
=========First token cost 0.3704 s and 8.169921875 GB=========
=========Rest tokens cost average 0.0240 s (158 tokens in all) and 8.169921875 GB=========
=========First token cost 0.3694 s and 8.169921875 GB=========
=========Rest tokens cost average 0.0239 s (144 tokens in all) and 8.169921875 GB=========
=========First token cost 0.3696 s and 8.169921875 GB=========
=========Rest tokens cost average 0.0237 s (88 tokens in all) and 8.169921875 GB=========
=========First token cost 0.3685 s and 8.169921875 GB=========
=========Rest tokens cost average 0.0234 s (143 tokens in all) and 8.169921875 GB=========
=========First token cost 0.3686 s and 8.169921875 GB=========
=========Rest tokens cost average 0.0236 s (263 tokens in all) and 8.169921875 GB=========
Inference time: 6.567069053649902 s

---------------------------W4A32------------------------------------------------
<class 'transformers_modules.modeling_qwen.QWenLMHeadModel'>
=========First token cost 3.4460 s and 9.96875 GB=========
=========Rest tokens cost average 0.0301 s (309 tokens in all) and 9.9765625 GB=========
=========First token cost 0.5011 s and 11.03515625 GB=========
=========Rest tokens cost average 0.0324 s (171 tokens in all) and 11.03515625 GB=========
=========First token cost 0.4391 s and 11.03515625 GB=========
=========Rest tokens cost average 0.0320 s (181 tokens in all) and 11.03515625 GB=========

**Comment by WeiguangHan** [comment]
We have tested it twice on your platform using the commands you given. Unlike your test, we have fixed the length of the output to a certain number. 
The first test result shows both the first token and rest token of W4A16 is a little faster than W4A32 on your machine when the input length is below 1K. But when the input length is over 1K, the rest token of W4A16 is slower than W4A32. The version of bigdl-llm is 2.5.0b20240314. 
The second test shows both the first token and rest token of W4A16 is  faster than W4A32. The version of bigdl-llm is 2.5.0b20240318. This is reasonable because we add the optimization for W4A16 since 15th Mar. Please refer to 
https://github.com/intel-analytics/BigDL/commit/77e9ef1221e175e858340f03fe67c4d90327d2c6 for more details.

**Comment by hkvision** [comment]
You can always use w4a16 with the latest bigdl-llm for better performance and memory.
We will update our example to use w4a16 as default.

**Comment by hkvision** [comment]
We have changed some examples to use fp16: https://github.com/intel-analytics/ipex-llm/pull/10528
Closing this issue.
