### ISSUE TITLE
the gap of performance between gegerate.py with all-in-one with batch 1 is too big

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10465]
benchmark chatglm3-6b with generate.py and W4A16, the performance is as below:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/bdaba5d7-616a-4cd0-8dd3-c4a6dced3c4e)

benchmark chatglm3-6b with all-in-one and W4A16, the performance is as below:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/040396c9-8185-42b9-937d-619f8537f9a4)

**Comment by chtanch** [comment]
I obtained similar token latencies for both scripts. Model precision is int4 with model.half(). Used `python/llm/dev/benchmark/benchmark_util.py` to benchmark generate.py

All-in-one benchmark:
|model            |1st token avg latency (ms)|2+ avg latency (ms/token)|encoder time (ms)|input/output tokens|batch_size|actual input/output tokens|num_beams|low_bit |cpu_embedding|model loading time (s)|peak mem (GB)|streaming|
|-----------------|--------------------------|-------------------------|-----------------|-------------------|----------|--------------------------|---------|--------|-------------|----------------------|-------------|---------|
|THUDM/chatglm3-6b|395.69                    |12.69                    |0.0              |1024-128           |1         |1032-128                  |1        |sym_int4|N/A          |6.2                   |4.873046875  |N/A      |

python/llm/example/GPU/PyTorch-Models/Model/chatglm3/generate.py:
![image](https://github.com/intel-analytics/BigDL/assets/33478814/58a4b045-2ae3-4acb-aa88-acae8e157a3e)

**Comment by hkvision** [comment]
Confirmed this is due to kernel 6.5 and setting `export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1`

Fix run-arc.sh in https://github.com/intel-analytics/BigDL/pull/10498

**Comment by Fred-cell** [comment]
Qwen-7B-Chat has the same issue for 2.5.0b20240322 version

**Comment by hkvision** [comment]
You need to `unset SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1`

**Comment by hkvision** [comment]
https://github.com/intel-analytics/ipex-llm/pull/10566
The problematic environment variable won't be set for kernel 6.5.
Issue fixed.
