### ISSUE TITLE
the memory issue about Llama-2-7B inference increases too high with >4k input prompt

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10479]
the gap between 4k and 2k input prompt is too large:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/1b53ad79-75b5-4b73-a802-0a3dcfe0c1db)

**Comment by hkvision** [comment]
We are fixing this in https://github.com/intel-analytics/BigDL/pull/10481 and https://github.com/intel-analytics/BigDL/pull/10490
Will be ready very soon.

**Comment by hkvision** [comment]
The memory usage should be improved using the latest nightly build. Please kindly check this :)
![image](https://github.com/intel-analytics/BigDL/assets/21994046/8e37456e-4965-491f-9c82-f30facb8b162)

**Comment by hkvision** [comment]
Synced with @Fred-cell for 4k input, memory issue resolved.
