### ISSUE TITLE
`bigdl-llm-init` can‘t properly set environments variable

### ISSUE THREAD

**Issue by Cyberpunk1210** [intel-analytics/ipex-llm#10478]
Hi team bigdl, `OMP_NUM_THREADS` and `LD_PRELOAD` can't seem to be set When I do `source bigdl-llm-init`  even though `env-chech.sh` has output the correct device information.

+++++ Env Variables +++++
LD_PRELOAD            = 
OMP_NUM_THREADS       = 
+++++++++++++++++++++++++
Complete.

Device Info
-----------------------------------------------------------------
PYTHON_VERSION=3.9.18
-----------------------------------------------------------------
transformers=4.31.0
-----------------------------------------------------------------
torch=2.1.0a0+cxx11.abi
-----------------------------------------------------------------
BigDL Version: 2.5.0b20240319
-----------------------------------------------------------------
ipex=2.1.10+xpu
-----------------------------------------------------------------
CPU Information: 
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             224
On-line CPU(s) list:                0-223
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8480+
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 56
Socket(s):                          2
Stepping:                           8
CPU max MHz:                        3800.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4000.00
-----------------------------------------------------------------
MemTotal:       528076344 kB
-----------------------------------------------------------------
xpu-smi is properly installed. 
-----------------------------------------------------------------

btw, Will `bigdl-llm-init` effectively impove training/inference time?

**Comment by MeouSker77** [comment]
this is because `intel-openmp` is not found.

`intel-openmp` provides `libiomp5.so`.

If you are using conda, then we assume `libiomp5.so` is located in `$CONDA_PREFIX/lib/libiomp5.so`, please check whether it exists. If not, please install it by `pip install intel-openmp`. If it already exists but still not found, please update to latest bigdl-llm and try again.

If you are not using conda, then we assume there should be such a directory tree:

```
- <dir>/
    - bin/
        - bigdl-init-init
    - lib/
        - libiomp5.so
```

 otherwise, `bigdl-llm-init` cannot find `libiomp5.so`
