### ISSUE TITLE
performance regression for llama2-7b between 0320 and 0319 version based on Xeon platform + Arc A770

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10495]
![image](https://github.com/intel-analytics/BigDL/assets/99886928/4f520381-4c9a-4a06-8c67-fd6faee8ae06)

**Comment by Fred-cell** [comment]
ubuntu22.04, kernel 6.5, oneapi: 2024.0.1

**Comment by chtanch** [comment]
I found no performance degradations from 0319 to 0320. There are improvements in some cases.

#### Settings
- Loop model.generate() 5 times after single warm-up
- Modify generate.py() to output benchmark. Added torch.xpu.empty_cache() after each model.generate().
- Did not set `export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1`
- Tested both with and without `BIGDL_QUANTIZE_KV_CACHE=1`
- Tested both 1k-512 and 2k-512 token prompts

**Comment by NovTi** [comment]
We cannot reproduce this issue, our results show there is no significant memory usage fluctuation between bigdl 320 and 319

```
320:
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375

319:
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
peak mem (GB): 5.490234375
```

**Comment by NovTi** [comment]
We did not see the performance regression between the 320 and 319 versions. Here is what we have for memory record

320:
peak mem (GB): 5.09765625
peak mem (GB): 5.09765625
peak mem (GB): 5.09765625
peak mem (GB): 5.09765625
peak mem (GB): 5.09765625

319:
peak mem (GB): 5.35546875
peak mem (GB): 5.35546875
peak mem (GB): 5.35546875
peak mem (GB): 5.35546875
peak mem (GB): 5.35546875


**Steps**:

1. `cd ~/test/ipex-llm/python/llm/dev/benchmark/all-in-one`
2. `conda activate bigdl-llm`
3. Set Quantized KV Cache `export BIGDL_QUANTIZE_KV_CACHE=1`
4. Replace the content of `/home/intel/test/ipex-llm/python/llm/dev/benchmark/all-in-one/config.yaml` to this setting:
```  
repo_id:
  - 'meta-llama/Llama-2-7b-chat-hf'
  - 'meta-llama/Llama-2-7b-chat-hf'
  - 'meta-llama/Llama-2-7b-chat-hf'
  - 'meta-llama/Llama-2-7b-chat-hf'
  - 'meta-llama/Llama-2-7b-chat-hf'
local_model_hub: '/home/intel/LLM'
warm_up: 1
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: 'sym_int4' # default to use 'sym_int4' (i.e. symmetric int4)
batch_size: 1 # default to 1
in_out_pairs:
  - '1024-512'
test_api:
  - "transformer_int4_gpu"  # on Intel GPU
cpu_embedding: False # whether put embedding to CPU (only avaiable now for gpu win related test_api)
streaming: False # whether output in streaming way (only avaiable now for gpu win related test_api)
```
5. Install the correct bigdl-llm version
6. `bash run-arc.sh`

**Comment by hkvision** [comment]
Should be the same as https://github.com/intel-analytics/ipex-llm/issues/10599 Issue fixed.
