### ISSUE TITLE
init-llama-cpp.bat not getting created in windows to use ipex[cpp] as the backend for llama.cpp

### ISSUE THREAD

**Issue by rahulunair** [intel-analytics/ipex-llm#10537]
Thank you building this incredible library!

I tried to set it up on a core ultra notebook, installing, to use ipex-llm as llama.cpp's backend to use my igpu.

After setting up the environment, gpu ipex, llm, drivers etc, i installed ipex-llm[cpp] using:

```bash
pip install --pre --upgrade ipex-llm[cpp]

```
But this is not adding `init-llama-cpp.bat` file anywhere. not in the scripts directory in my .local env .

I followed the instructions from the doc here: https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Quickstart/llama_cpp_quickstart.html

Could you kindly let me know if there is a setup is missing in the steps or if i did something wrong?

**Comment by rnwang04** [comment]
Hi @rahulunair , if you follow below steps to create a llm-cpp conda env and pip install ipex-llm[cpp],
```bash
conda create -n llm-cpp python=3.9
conda activate llm-cpp
pip install --pre --upgrade ipex-llm[cpp]
```
then the `init-llama-cpp.bat` has been added into your conda env's site-packages, and you can execute it in any directory, but please make sure run `init-llama-cpp.bat` **with administrator privilege in Anaconda Prompt with the same conda env** like `(llm-cpp) C:\Users\xxx>init-llama-cpp.bat`.
