### ISSUE TITLE
IPEX-LLM vLLM support 4 socket machine？

### ISSUE THREAD

**Issue by Storm0921** [intel-analytics/ipex-llm#10567]
May I ask if IPEX-LLM supports the startup method of the vLLM API server with 4 sockets?
![image](https://github.com/intel-analytics/ipex-llm/assets/57557769/438b9d80-6525-4949-a189-970edd1e7ef4)

**Comment by gc-fu** [comment]
Hi, starting the vLLM api_server across multiple sockets will have bad impact on inference speed due inconsistent access speed to memories.

You can start the vLLM server across all the CPU cores.  However, our recommendation is to start the `api_server` in one socket.

In your config, that should be:
```bash
numactl -C 0-31 -m 0 python3 xxxx/api_server.py
```

We also recommend to use `source bigdl-llm-init -t` before starting the service.

If you do not set anything, it will by default use all the cores from 4 sockets.

**Comment by Storm0921** [comment]
> Hi, starting the vLLM api_server across multiple sockets will have bad impact on inference speed due inconsistent access speed to memories.
> 
> You can start the vLLM server across all the CPU cores. However, our recommendation is to start the `api_server` in one socket.
> 
> In your config, that should be:
> 
> ```shell
> export OMP_NUM_THREADS=32
> numactl -C 0-31 -m 0 python3 xxxx/api_server.py
> ```
> 
> We also recommend to use `source ipex-llm-init -t` before starting the service.
> 
> If you do not set anything, it will by default use all the cores from 4 sockets.

ok, thank you!
