### ISSUE TITLE
Ubuntu22.04  can not  update gpu driver. Seems Like intel repo has somethings wrong!

### ISSUE THREAD

**Issue by zhangjizxc** [intel-analytics/ipex-llm#10595]
```
wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
  sudo gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg
echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy client" | \
  sudo tee /etc/apt/sources.list.d/intel-gpu-jammy.list
sudo apt update

```

Get:6 https://repositories.intel.com/gpu/ubuntu jammy/client i386 Packages [38.8 kB]
Err:6 https://repositories.intel.com/gpu/ubuntu jammy/client i386 Packages
  File has unexpected size (27855 != 38755). Mirror sync in progress? [IP: [143.204.98.24](http://143.204.98.24/) 443]
  Hashes of expected file:
   - Filesize:38755 [weak]
   - SHA512:67b3cfe9c0e604f37f3be8aebf8fc7053cb4f9e9f4c72ef0f3df00f319efb3238ae968dbf2a9b7b48b5eb4a86327a8375554d379a31b0fc4721b846f5be7d164
   - SHA256:2d1e839daef74487a1cee97e844cc551eecfc734cc63d5a400ee12693e71237c
   - SHA1:c7c287d5377bde83e82b3e85fbfff0ff3656eff2 [weak]
   - MD5Sum:d1d955f53c3eb262e2ed9f876ca76f5f [weak]
  Release file created at: Sat, 23 Mar 2024 12:06:07 +0000
Get:7 https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages [97.9 kB]
Err:7 https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
  
Reading package lists... Done  
E: Failed to fetch https://repositories.intel.com/gpu/ubuntu/dists/jammy/client/binary-i386/Packages.gz  File has unexpected size (27855 != 38755). Mirror sync in progress? [IP: [143.204.98.24](http://143.204.98.24/) 443]
   Hashes of expected file:
    - Filesize:38755 [weak]
    - SHA512:67b3cfe9c0e604f37f3be8aebf8fc7053cb4f9e9f4c72ef0f3df00f319efb3238ae968dbf2a9b7b48b5eb4a86327a8375554d379a31b0fc4721b846f5be7d164
    - SHA256:2d1e839daef74487a1cee97e844cc551eecfc734cc63d5a400ee12693e71237c
    - SHA1:c7c287d5377bde83e82b3e85fbfff0ff3656eff2 [weak]
    - MD5Sum:d1d955f53c3eb262e2ed9f876ca76f5f [weak]
   Release file created at: Sat, 23 Mar 2024 12:06:07 +0000
E: Failed to fetch https://repositories.intel.com/gpu/ubuntu/dists/jammy/client/binary-amd64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by qiuxin2012** [comment]
We didn't meet this error before. I just check the error message on ark ubuntu https://askubuntu.com/questions/1147254/apt-update-fails-at-chrome-stable-main-file-has-unexpected-size-1103-1104, it looks like a repository server problem, you can try again with 
```
sudo apt clean
sudo apt update
```
