### ISSUE TITLE
inference Llama-2-13b-chat with W4A16, the latency of next token with 1k input is slower than 2k input

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10599]
for 1k input the performance is as below:
0,meta-llama/Llama-2-13b-chat-hf,820.0,46.15,0.0,1024-512,1,1025-324,1,sym_int4,N/A,17.19,0.0,N/A
for 2k input the performance is as below:
0,meta-llama/Llama-2-13b-chat-hf,1596.1,28.57,0.0,2048-512,1,2049-512,1,sym_int4,N/A,17.1,0.0,N/A

**Comment by zhentaocc** [comment]
see comment in https://github.com/intel-analytics/ipex-llm/issues/10598#issuecomment-2029286585

**Comment by hkvision** [comment]
Same as https://github.com/intel-analytics/ipex-llm/issues/10598
