### ISSUE TITLE
The current vLLM docker image can't support the Qwen 1.5 7B model because of transformer version 

### ISSUE THREAD

**Issue by darshanhuang1** [intel-analytics/ipex-llm#10684]
Error message as the screenshot attached. Transformer version is lower than required, but failed after upgraded manually.
<img width="1065" alt="a6c6e0e7ffc4ddf7447be6f5e70ef8a" src="https://github.com/intel-analytics/ipex-llm/assets/18653857/fbeb3bd2-9dbd-4bb1-91c5-e974d5072d32">

**Comment by xiangyuT** [comment]
We have updated image `intelanalytics/ipex-llm-serving-vllm-cpu:2.1.0-SNAPSHOT` to support model `Qwen1.5-7B-Chat` with a proper transformers version. You could have a try with this new image.

**Comment by darshanhuang1** [comment]
new image is fine, thanks!
