### ISSUE TITLE
Batch size 16, GPU utilization 100%, Request 100% error

### ISSUE THREAD

**Issue by darshanhuang1** [intel-analytics/ipex-llm#10751]
Batch size 16(16 channel concurrency, and vllm internally switches to batch), GPU utilization 100%, Request 100% error, the model will report an error, and then initiate a shorter request separately, which will also report an error, unless the model is restarted. Test parameters as below:
prompt_tokens:771
completion_tokens:587
total_tokens:1358
batch size=16

In addition, the GPU utilization is approximately 91.1% at 4 concurrent and 100% at 8 concurrent.  CPU is fine when 128 concurrent. 
test data as below：
{
    "prompt": "<|im_start|>system\n您是专业的智能翻译助手，任务是将用户的输入翻译成英文。以下是一些重要的翻译原则：\n1.将尽力确保翻译的准确性和流畅性。\n2.翻译后的句子将完全使用英文，不会出现其他非英文单词。\n3.如果用户的输入含有特定的专业术语或者是特定领域的语言，将尽力保持这些术语在翻译后的准确性。\n4.将尊重所有用户，不会进行任何形式的歧视或偏见。\n5.将遵守所有的隐私规定，不会存储或分享用户的任何信息。<|im_end|>\n<|im_start|>user\n在一个遥远的星球上，有一个叫做“光明之城”的地方。这个城市的居民都是一些非常聪明的生物，他们有着高超的科技和深厚的文化底蕴。他们的生活方式和我们大不相同，他们的社会是以知识和智慧为基础的，而不是金钱或权力。\n在光明之城的中心，有一座巨大的图书馆，这里收藏了这个星球上所有的知识和智慧。这个图书馆的规模之大，足以让任何一个地球上的图书馆都相形见绌。这里的书籍不仅包括了科学、艺术、哲学等各个领域的知识，还有一些我们地球人无法理解的神秘学问。\n这个图书馆的管理员是一个叫做“千眼”的生物，他有着一千只眼睛，可以同时阅读一千本书籍。他的聪明才智让所有的城市居民都对他充满了敬仰。他不仅是这个图书馆的管理员，也是这个城市的领导者，他用他的知识和智慧引导着这个城市的发展。\n然而，即使在这样一个充满光明和知识的城市中，也存在着黑暗和无知。在城市的边缘，有一群被称为“暗影人”的生物，他们拒绝接受知识，只相信他们的感觉和直觉。他们的生活方式和光明之城的居民截然不同，他们的社会是以力量和恐惧为基础的。\n千眼虽然是一个非常聪明的生物，但他并不是无所不能的。他无法理解暗影人为什么会拒绝知识，也无法改变他们的生活方式。他试图用他的知识和智慧去启蒙他们，但是他的努力都以失败告终。\n然而，千眼并没有因此而放弃。他相信，只要他坚持下去，总有一天，他能够用他的知识和智慧点亮这个城市的每一个角落，让所有的生物都能享受到知识的光辉。\n这就是千眼的故事，他是一个充满智慧和坚韧的生物，他的故事告诉我们，知识是光明，无知是黑暗，只有通过知识，我们才能驱散黑暗，走向光明。\n在光明之城的边缘，千眼站在高高的城墙上，凝视着暗影人的领地。他的一千只眼睛闪烁着智慧的光芒，他的心中充满了决心和希望。\n他知道，他不能强迫暗影人接受知识，他必须找到一种方法，让他们自愿地接受知识的光辉。于是，他决定去暗影人的领地，尝试理解他们的生活方式，找到一个可以让他们接受知识的方法。\n千眼走进了暗影人的领地，他看到了他们的生活方式，他看到了他们的恐惧和无知。他试图和他们交流，但他们对他的知识和智慧感到恐惧和排斥。\n然而，千眼并没有因此而放弃。他开始学习暗影人的语言，他开始理解他们的文化，他开始尝试用他们能理解的方式来传递知识。\n经过了很长时间的努力，千眼终于找到了一个方法。他开始用故事的形式来传递知识，他用他们能理解的语言和文化来讲述知识的故事。\n暗影人开始对千眼的故事产生了兴趣，他们开始听他讲述的故事，他们开始理解和接受知识的光辉。\n这就是千眼的故事，他用他的智慧和坚韧，点亮了一个充满黑暗和无知的地方，他用他的知识和智慧，改变了一个社会，他用他的故事，让所有的生物都能享受到知识的光辉。<|im_end|>\n<|im_start|>assistant\n",
    "model": "Qwen1.5-7B-Chat",
    "temperature": 0,
    "max_tokens": 1024
}

error message screenshot as below:
<img width="524" alt="fac944fbe3a00c77260dbe41d4319ba" src="https://github.com/intel-analytics/ipex-llm/assets/18653857/7427ed32-1eae-4aa5-9314-a3e04d186231">

**Comment by gc-fu** [comment]
Hi, I have reproduced this issue.  The issue is caused by out of XPU memory on Arc A770.

For this kind of quite long sequence, I would recommend to use the following config for testing:

--gpu-memory-utilization 0.75
--max-num-seqs 12

**Comment by darshanhuang1** [comment]
after optimization and parameters updated, the issue is resolved.
