### ISSUE TITLE
llama 3 can not load_low_bit

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#10816]
I save llama 3 in int4 and get two bin files:
pytorch_model-00001-of-00002.bin
pytorch_model-00002-of-00002.bin

But I can load them with load_low_bit, because  can not find pytorch_model.bin.
I find that for 13B model, the model save as a pytorch_model.bin before and is loaded successfully.

version:
```
bigdl-core-xe-21              2.5.0b20240418
bigdl-llm                     2.5.0b20240418
```

**Comment by glorysdj** [comment]
please try ipex-llm to run llama3

**Comment by violet17** [comment]
It works. Thanks.
