### ISSUE TITLE
[vLlm-serving] When run "VLLM_BUILD_XPU_OPS=1 pip install --no-build-isolation -v -e . ", it reports can't find dpct.hpp

### ISSUE THREAD

**Issue by johnysh** [intel-analytics/ipex-llm#10825]
I followed the steps to install vLlm-serving , but when ran VLLM_BUILD_XPU_OPS=1 pip install --no-build-isolation -v -e ., it reports an error couldn't find dpct.hpp
log  as below:
/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/intel_extension_for_pytorch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/include/python3.11 -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -O2 -g -DNDEBUG -std=gnu++17 -fPIC -DVLLM_BUILD_XPU_OPS -fsycl -fsycl-targets=spir64 -D_GLIBCXX_USE_CXX11_ABI=1 -MD -MT CMakeFiles/_C.dir/csrc/xpu/layernorm_xpu.cpp.o -MF CMakeFiles/_C.dir/csrc/xpu/layernorm_xpu.cpp.o.d -o CMakeFiles/_C.dir/csrc/xpu/layernorm_xpu.cpp.o -c /home/intel/vllm/csrc/xpu/layernorm_xpu.cpp
  /home/intel/vllm/csrc/xpu/layernorm_xpu.cpp:6:10: fatal error: 'dpct/dpct.hpp' file not found
      6 | #include <dpct/dpct.hpp>
        |          ^~~~~~~~~~~~~~~
  1 error generated.
  [3/9] Building CXX object CMakeFiles/_C.dir/csrc/xpu/cache_ops_xpu.cpp.o
  FAILED: CMakeFiles/_C.dir/csrc/xpu/cache_ops_xpu.cpp.o
  ccache icpx -DTORCH_EXTENSION_NAME=_C -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -D_C_EXPORTS -I/home/intel/vllm/csrc -I/opt/intel/oneapi/compiler/2024.0/include/sycl -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/intel_extension_for_pytorch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/include/python3.11 -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -O2 -g -DNDEBUG -std=gnu++17 -fPIC -DVLLM_BUILD_XPU_OPS -fsycl -fsycl-targets=spir64 -D_GLIBCXX_USE_CXX11_ABI=1 -MD -MT CMakeFiles/_C.dir/csrc/xpu/cache_ops_xpu.cpp.o -MF CMakeFiles/_C.dir/csrc/xpu/cache_ops_xpu.cpp.o.d -o CMakeFiles/_C.dir/csrc/xpu/cache_ops_xpu.cpp.o -c /home/intel/vllm/csrc/xpu/cache_ops_xpu.cpp
  /home/intel/vllm/csrc/xpu/cache_ops_xpu.cpp:6:10: fatal error: 'dpct/dpct.hpp' file not found
      6 | #include <dpct/dpct.hpp>
        |          ^~~~~~~~~~~~~~~
  1 error generated.
  [4/9] Building CXX object CMakeFiles/_C.dir/csrc/xpu/attention_xpu.cpp.o
  FAILED: CMakeFiles/_C.dir/csrc/xpu/attention_xpu.cpp.o
  ccache icpx -DTORCH_EXTENSION_NAME=_C -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -D_C_EXPORTS -I/home/intel/vllm/csrc -I/opt/intel/oneapi/compiler/2024.0/include/sycl -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/intel_extension_for_pytorch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/include/python3.11 -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include -isystem /home/intel/miniconda3/envs/ipex-vllm/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -O2 -g -DNDEBUG -std=gnu++17 -fPIC -DVLLM_BUILD_XPU_OPS -fsycl -fsycl-targets=spir64 -D_GLIBCXX_USE_CXX11_ABI=1 -MD -MT CMakeFiles/_C.dir/csrc/xpu/attention_xpu.cpp.o -MF CMakeFiles/_C.dir/csrc/xpu/attention_xpu.cpp.o.d -o CMakeFiles/_C.dir/csrc/xpu/attention_xpu.cpp.o -c /home/intel/vllm/csrc/xpu/attention_xpu.cpp
  /home/intel/vllm/csrc/xpu/attention_xpu.cpp:6:10: fatal error: 'dpct/dpct.hpp' file not found
      6 | #include <dpct/dpct.hpp>

**Comment by gc-fu** [comment]
Hi, I am working on to reproduce this issue.  Will update to this thread.

**Comment by gc-fu** [comment]
My installment according to this https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/vLLM-Serving#1-install-1 succussed without error.

Can you check your `oneAPI` version through:

```
source /opt/intel/oneapi/setvars.sh
dpcpp --version
```

**Comment by johnysh** [comment]
(ipex-vllm) intel@intel-0:~/vllm$ source /opt/intel/oneapi/setvars.sh --force
 
:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.1.16(1)-release
   args: Using "$@" for setvars.sh arguments: --force
:: ccl -- latest
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpl -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: oneAPI environment initialized ::
 
(ipex-vllm) intel@intel-0:~/vllm$ dpcpp --version
icpx: warning: use of 'dpcpp' is deprecated and will be removed in a future release. Use 'icpx -fsycl' [-Wdeprecated]
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.2 (2024.0.2.20231213)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2024.0/bin/compiler
Configuration file: /opt/intel/oneapi/compiler/2024.0/bin/compiler/../icpx.cfg
(ipex-vllm) intel@intel-0:~/vllm$

**Comment by gc-fu** [comment]
Hi, can you search for file "dpct.hpp"?

In my environment, it shows that it is located in oneAPI install dir:
![image](https://github.com/intel-analytics/ipex-llm/assets/110874468/6f466e4a-b34b-460c-a262-7f12eb95caeb)

**Comment by gc-fu** [comment]
I will try to reproduce this issue according to your config.

**Comment by johnysh** [comment]
I  uninstall before it ,  and use this cmd to install again 
 sudo bash ./l_BaseKit_p_2024.0.1.46_offline.sh -a --silent --eula accept --install-dir=/opt/intel/oneapi
then could find header file and compile successfully ,  but I don't know why previous oneapi install cmd couldn't install successfully.

**Comment by johnysh** [comment]
when I run "pip install interegular cloudpickle diskcache joblib lark nest-asyncio numba scipy", I meet
![image](https://github.com/intel-analytics/ipex-llm/assets/15604431/3ed317dc-ee00-4e43-aac6-2386a07e2e94)

Can I ignore  it？

**Comment by gc-fu** [comment]
Yes, you can ignore it.

**Comment by gc-fu** [comment]
This problem is caused by not installing this package:
intel-oneapi-dpcpp-ct-2024.0 through apt-get

**Comment by gc-fu** [comment]
Closed.

If you still have problems, feel free to reopen this.
