### ISSUE TITLE
Update Ollama Version to 0.1.32

### ISSUE THREAD

**Issue by Quallyjiang** [intel-analytics/ipex-llm#10837]
Ollama supports OpenAI API since 0.1.24. OpenAI API support is quite important for us. Could we update ollama version in ipex-llm[cpp] package to latest release like 0.1.32? I'm interested in windows platform.

**Comment by sgwhat** [comment]
Hi @Quallyjiang, ipex-llm ollama has been updated into v0.1.32.

**Comment by Quallyjiang** [comment]
thanks!
