### ISSUE TITLE
qwen 1.5 error with intelanalytics/ipex-llm-xpu:2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by zhm-algo** [intel-analytics/ipex-llm#10834]
![Image](https://github.com/intel-analytics/ipex-llm/assets/68285535/a617023f-2cf6-491a-a27f-3155bb21d27a)

**Comment by gc-fu** [comment]
Can you try this image intelanalytics/ipex-llm-serving-vllm-xpu:2.1.0-SNAPSHOT?

From the figure you posted, it seems that you try to run vllm-v2 in `intelanalytics/ipex-llm-xpu:2.1.0-SNAPSHOT`.  However, this image does not provide the service.

**Comment by gc-fu** [comment]
Closed as completed.
