### ISSUE TITLE
Can provide llama.dll build guide？

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/ipex-llm#10875]
ipex-llm llama.cpp has provided exe solution when build.
Can ipex-llm support to build llama.dll, llava_shard.dll, ggml_shard.dll ? dll can put into APP.

https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Quickstart/llama_cpp_quickstart.html

**Comment by sgwhat** [comment]
Also `ggml_shard.dll`, `llava_shard.dll`.

**Comment by rnwang04** [comment]
Hi @KiwiHana ,
We have added llama.dll, llava_shard.dll, ggml_shard.dll into ipex-llm[cpp] windows release.
You can have a try with our today's new release.
