### ISSUE TITLE
failed to run piqa test with sym_int4 precison by harness 

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/ipex-llm#10961]
(env_p311) C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness>python run_llb.py --model ipex-llm --pretrained "C:\AIGC\hf\Meta--Llama-3-8B-Instruct" --precision sym_int4 --device xpu --tasks piqa --batch 1 --no_cache
Could not import signal.SIGPIPE (this is expected on Windows machines)
C:\ProgramData\anaconda3\envs\env_p311\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\ProgramData\anaconda3\envs\env_p311\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-05-08 13:50:54,841 - INFO - intel_extension_for_pytorch auto imported
Selected Tasks: ['piqa']
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████| 4/4 [00:00<00:00,  8.79it/s]
2024-05-08 13:50:55,690 - INFO - Converting the current model to sym_int4 format......
Using the latest cached version of the dataset since piqa couldn't be found on the Hugging Face Hub
2024-05-08 13:51:38,088 - WARNING - Using the latest cached version of the dataset since piqa couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'plain_text' at C:\Users\Administrator\.cache\huggingface\datasets\piqa\plain_text\1.1.0\2e8ac2dffd59bac8c3c6714948f4c551a0848bb0 (last modified on Tue Apr 23 15:09:12 2024).
2024-05-08 13:51:38,097 - WARNING - Found the latest cached dataset configuration 'plain_text' at C:\Users\Administrator\.cache\huggingface\datasets\piqa\plain_text\1.1.0\2e8ac2dffd59bac8c3c6714948f4c551a0848bb0 (last modified on Tue Apr 23 15:09:12 2024).
Task: piqa; number of docs: 1838
Task: piqa; document 0; context prompt (starting on next line):
Question: Remove seeds from  strawberries
Answer:
(end of prompt on previous line)
Requests: [Req_loglikelihood('Question: Remove seeds from  strawberries\nAnswer:', ' Blend the strawberries, pour the mixture through a fine-mesh strainer with a bowl underneath to catch the pulps and strain out the seeds')[0]
, Req_loglikelihood('Question: Remove seeds from  strawberries\nAnswer:', ' Chop up the strawberries, pour the mixture through a fine-mesh strainer with a bowl underneath to catch the pulps and strain out the seeds')[0]
]
Running loglikelihood requests
  9%|█████▎                                                    | 337/3676 [05:33<55:02,  1.01it/s]
Job config of task=piqa, precision=sym_int4 failed. Error Message: unsupported dtype, only fp32 and fp16 are supported
Here are results of all successful tasks:
Traceback (most recent call last):
  File "C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness\run_llb.py", line 150, in <module>
    main()
  File "C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness\run_llb.py", line 146, in main
    raise RuntimeError('\n'.join(fail))
RuntimeError: Job config of task=piqa, precision=sym_int4 failed. Error Message: unsupported dtype, only fp32 and fp16 are supported

**Comment by pengyb2001** [comment]
```
100%|██████████████████████████████████████████████████████████████████████████████████████| 3676/3676 [04:18<00:00, 14.
24it/s]
{
  "results": {
    "piqa": {
      "acc": 0.7665941240478781,
      "acc_stderr": 0.009869247889521012,
      "acc_norm": 0.7731229597388466,
      "acc_norm_stderr": 0.009771584259215168
    }
  },
  "versions": {
    "piqa": 0
  },
  "config": {
    "model": "ipex-llm",
    "model_args": "pretrained=/mnt/disk1/Meta-Llama-3-8B-Instruct,load_in_low_bit=sym_int4",
    "num_fewshot": 0,
    "batch_size": "1",
    "batch_sizes": [],
    "device": "xpu",
    "no_cache": true,
    "limit": null,
    "bootstrap_iters": 100000,
    "description_dict": {}
  }
}
Here are results of all successful tasks:
{'model': 'ipex-llm', 'model_args': 'pretrained=/mnt/disk1/Meta-Llama-3-8B-Instruct,load_in_low_bit=sym_int4', 'num_fewshot': 0, 'batch_size': '1', 'batch_sizes': [], 'device': 'xpu', 'no_cache': True, 'limit': None, 'bootstrap_iters': 100000, 'description_dict': {}}
|Task|Version| Metric |Value |   |Stderr|
|----|------:|--------|-----:|---|-----:|
|piqa|      0|acc     |0.7666|±  |0.0099|
|    |       |acc_norm|0.7731|±  |0.0098|
```
Hi, the above is my test result, I did not encounter the situation you said. Here is my env, please try checking you env and other settings.
```
-----------------------------------------------------------------
-e PYTHON_VERSION=3.11.9
-----------------------------------------------------------------
transformers=4.37.0
-----------------------------------------------------------------
torch=2.1.0a0+cxx11.abi
-----------------------------------------------------------------
ipex-llm Version: 2.1.0b20240509
-----------------------------------------------------------------
ipex=2.1.10+xpu

Device Name: Intel(R) Data Center GPU Max 1100
```

**Comment by aoke79** [comment]
I used the MTL iGPU, not Data Center GPU. might you please have a try on MTL? if you need env, I can share my env to you.
thanks

**Comment by aoke79** [comment]
BTW: today, when I tried to update the lib, it appears some error, please refer the capture for details.
![ipex-llm-error-cap](https://github.com/intel-analytics/ipex-llm/assets/7357656/df43e1f6-dd6d-40dc-89ba-242307848e04)

**Comment by aoke79** [comment]
I can't update transformers to 4.37.0, it remains to 4.31.0, which one I should use? 
thanks a lot,

**Comment by aoke79** [comment]
set BIGDL_QUANTIZE_KV_CACHE=0

**Comment by pengyb2001** [comment]
The default setting for mtl is to enable the quantize kv cache. In the model, `llama_attention_forward_4_36_quantized` is used where `key_states` and `value_states` are updated with inputs that are in bf16 format, which leads to an issue with `append_fp8_kv_cache`. The method `linear_q4_0.quantize_key_value(key, value)` also receives bf16 inputs. However, MTL lacks native support for bf16, which is required by the new rms norm kernel, resulting in an error. Since fp16 is faster than bf16, there is no need to add bf16 support. This issue does not occur on arc. On mtl, setting `IPEX_LLM_QUANTIZE_KV_CACHE=0` (previously `BIGDL_QUANTIZE_KV_CACHE`) can avoid this problem. Alternatively, converting `key` and `value` to fp16 before passing them to `append_fp8_kv_cache linear_q4_0.quantize_key_value` can also resolve the error.

**Comment by pengyb2001** [comment]
1. In the llama3 model, the dtype for the `key` and `value` values passed into `linear_q4_0.quantize_key_value` defaults to bf16. However, MTL does not have native bf16 support, so this will cause an error.
2. On Arc, `QUANTIZE_KV_CACHE` is not enabled by default, whereas it is on MTL. Thus, this method does not produce an error on Arc.
3. When running the benchmark harness on MTL, setting `IPEX_LLM_QUANTIZE_KV_CACHE=0` (previously `BIGDL_QUANTIZE_KV_CACHE`) can avoid this issue. Alternatively, converting key and value to fp16 before passing them to ‘linear_q4_0.quantize_key_value’ can also resolve the error.
