### ISSUE TITLE
[bug] LLAMA3-8B输出错误

### ISSUE THREAD

**Issue by intelyoungway** [intel-analytics/ipex-llm#10974]
依赖包: transformers==4.31.0 # 问题出在这里, 需要 版本>4.33.0
1. 模型: Meta-Llama-3-8B-Instruct
2. 精度: asym_int4 或 bf16
3. 设备: SPR9468 (Quadrant, HBM Flat, cpuset 0-11cores, mem 2)
4. 输入: 见附件1
[prompt_medical_1k.txt](https://github.com/intel-analytics/ipex-llm/files/15259351/prompt_medical_1k.txt)
5. 代码: 见附件2
6. 命令: python step2_simple_chat.py --prompt "\`cat prompt_medical_1k.txt\`"
[step2_simple_chat.zip](https://github.com/intel-analytics/ipex-llm/files/15259405/step2_simple_chat.zip)
7. 问题:
返回的输出是乱码 例如 
![乱码issue](https://github.com/intel-analytics/ipex-llm/assets/99377901/39a166c8-41f4-4d24-84e9-04fbc86c633e)

**Comment by hzjane** [comment]
@intelyoungway  What version of transformers are you using? transformers>=4.33.0 is required for Llama3 with IPEX-LLM optimizations. You can try to run `pip install transformers==4.37.0` and test it again.

**Comment by intelyoungway** [comment]
解决了，确实是transformers版本问题，安装4.37.0之后就好了

**Comment by hzjane** [comment]
> 解决了，确实是transformers版本问题，安装4.37.0之后就好了 所以，能否把ipex-llm的docker镜像中的transformers版本更新一下，看起来这个版本依然是旧的。或者 在examples中提示用户手动安装新的版本。毕竟不同模型需要的版本似乎也不同

We have provide different install guide for different examples like [this](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/llama3#1-install). But it may not be updated yet in the latest docker. Could you please provide the old example link for me to update?

**Comment by intelyoungway** [comment]
I think it is my fault, I simply use the script w/o notice of the installation.
I think the current README LGTM!
Thanks!

**Comment by jason-dai** [comment]
> > 解决了，确实是transformers版本问题，安装4.37.0之后就好了 所以，能否把ipex-llm的docker镜像中的transformers版本更新一下，看起来这个版本依然是旧的。或者 在examples中提示用户手动安装新的版本。毕竟不同模型需要的版本似乎也不同
> 
> We have provide different install guide for different examples like [this](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/llama3#1-install) to install extral libs. But it may not be updated yet in the latest docker. Could you please provide the old example link for me to update?

Maybe we should highlight the requirement, similar to https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/mixtral#requirements
