### ISSUE TITLE
Run neural-chat 7b inference with Deepspeed on Flex 140. #10507

### ISSUE THREAD

**Issue by weiseng-yeap** [intel-analytics/ipex-llm#10983]
Hi,

After review the previous issue : https://github.com/intel-analytics/ipex-llm/issues/10507.

We tested on Flex140 same suggestion, we get the performance very slow on Flex140 with both GPU running.

[Env.txt](https://github.com/intel-analytics/ipex-llm/files/15273187/Env.txt)

The xpu-smi GPU just usage very low. Suppose is 12GB/2 each GPU is 6GB.
Attached the platform setup configuration, see any need to addon. 
![MicrosoftTeams-image (1)](https://github.com/intel-analytics/ipex-llm/assets/49100840/efda433b-5392-41b0-80cb-23cd4ec2de79)
![MicrosoftTeams-image](https://github.com/intel-analytics/ipex-llm/assets/49100840/d715b090-89b5-4dcf-9839-3641016aaf58)

**Comment by plusbang** [comment]
Hi, @weiseng-yeap , we had some update in our env-check script. Could you please try the new script (https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts) and attach related information?

Besides, the used GPU memory is mainly related to the model size, applied precision and input length. According to your screenshot, the GPU power is very low.

**Comment by weiseng-yeap** [comment]
Hi BinBin

Using latest script with attached latest log.
[Env_V2.txt](https://github.com/intel-analytics/ipex-llm/files/15288849/Env_V2.txt)

**Comment by plusbang** [comment]
> 
> Using latest script with attached latest log. [Env_V2.txt](https://github.com/intel-analytics/ipex-llm/files/15288849/Env_V2.txt)

It seems `intel-fw-gpu` and `intel-i915-dkms` is not installed. Please try `sudo apt install intel-i915-dkms intel-fw-gpu` first.

**Comment by weiseng-yeap** [comment]
Attached with latest env. 
[Uploading Env_V3.txt…]()
