### ISSUE TITLE
ipex-llm version 0510 has regression than 0430, especially for BS=16,32 and 8k input

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10994]
![image](https://github.com/intel-analytics/ipex-llm/assets/99886928/170606f7-4466-4aaa-85d8-309c410bd5b1)

**Comment by lalalapotter** [comment]
Please enable low memory mode and check if this issue still exists. You could use export IPEX_LLM_LOW_MEM=1 to enable low memory mode.

**Comment by lalalapotter** [comment]
Do not observe performance regression in stable release validation test, close issue for now.
