### ISSUE TITLE
all-in-one tool for ChatGLM3-6b: next token latency with BS=16 is slower than before

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10993]
ipex-llm version: 2.5.0b20240510
![image](https://github.com/intel-analytics/ipex-llm/assets/99886928/2753c97e-5b75-4d95-bb9a-fb75e2dd6c44)

**Comment by lalalapotter** [comment]
Please enable low memory mode and check if this issue still exists. You could use `export IPEX_LLM_LOW_MEM=1` to enable low memory mode.

**Comment by hkvision** [comment]
Duplicate with: https://github.com/intel-analytics/ipex-llm/issues/10994
Closing this issue and will update in that one.
