### ISSUE TITLE
about conflict 

### ISSUE THREAD

**Issue by K-Alex13** [intel-analytics/ipex-llm#11069]
<img width="927" alt="image" src="https://github.com/intel-analytics/ipex-llm/assets/74948610/67808bd8-67ec-47f2-a6ab-ea37e2cc4a73">
Not sure what happened here.  The packages I installed many times before as following:
<img width="669" alt="image" src="https://github.com/intel-analytics/ipex-llm/assets/74948610/ce4e11ef-5d64-41bc-8693-1dca2ec1d9b0">
But now comes up the conflict issue.  Please help me

**Comment by qiuxin2012** [comment]
bigdl-llm has now become ipex-llm, please use new ipex-llm, see the [installation guide](https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#install-ipex-llm).

**Comment by K-Alex13** [comment]
thank you very much it works now
