### ISSUE TITLE
Phi3-4k winograde drop from 0515 version to 0516 version

### ISSUE THREAD

**Issue by Quallyjiang** [intel-analytics/ipex-llm#11073]
microsoft/Phi-3-mini-4k-instruct model score on winograde dropped from 0.6958 (0515) to 0.4933 (0516).
transformers version 4.37.2. 
quantization sym_int4. compute on fp16. iGPU mtl platform.

**Comment by lalalapotter** [comment]
Cannot reproduce on ARC, will try it on MTL.

**Comment by lalalapotter** [comment]
Cannot reproduce the accuracy issue on MTL as well, could you please share the modification methods for running qtype=sym_int4 and dtype=fp16, maybe some changes in code or shell scripts.

**Comment by lalalapotter** [comment]
After sync with user offline, we can reproduce the issue by following command, when batch=8:

```shell
python run_llb.py --model ipex-llm --pretrained /path/to/model/Phi-3-mini-4k-instruct/ --precision sym_int4 --device xpu --tasks winogrande --batch 8 --no_cache
```

will investigate the root cause and get back to you ASAP.
