### ISSUE TITLE
need an easy way to roll back driver installs

### ISSUE THREAD

**Issue by donbright** [intel-analytics/ipex-llm#11139]
It would be very helpful to users to have an easy way to uninstall the drivers. 

I was trying to follow https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Quickstart/install_linux_gpu.html and my system became unstable after installing the drivers, in fact it would not stay up more than a few minutes without the entire machine hard locking. 

Trying to uninstall the drivers 'manually' resulted in a system that won't boot correctly. I will have to rebuild and probably reinstall the OS.

**Comment by qiuxin2012** [comment]
The packages in our guide are all installed using apt, you can uninstall them using apt again.
Maybe you can look this blog for help https://www.cyberciti.biz/howto/debian-linux/ubuntu-linux-rollback-an-apt-get-upgrade/

**Comment by donbright** [comment]
the instructional site that i link to does not just use apt, it also installs custom apt sources for intel and its difficult to tell which packages are from that intel site versus from ubuntu. 

it would be easier to have an uninstall script or at least a warning up top that it can cause your machine to become  unusable. (+ advice to use a Timeshift save point or something similar)

**Comment by qiuxin2012** [comment]
Which package is not installed with `apt install`？ Only conda, but conda is installed to your home dir, it won't affect your operating system.
Maybe we can advice users to backup their package list with `apt-clone` before they start the installation.
