### ISSUE TITLE
about test 3 Gpu with ipex

### ISSUE THREAD

**Issue by K-Alex13** [intel-analytics/ipex-llm#11152]
I try to test two gpu with following link:
https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/example/GPU/Deepspeed-AutoTP/run_qwen_14b_arc_2_card.sh
If I want to test three gpu, what should I do.

**Comment by plusbang** [comment]
Hi, @K-Alex13 , as we introduced in our readme, you could change `NUM_GPUS` to the number of GPUs you have on your machine. 

But considering that the shape of the linear layer is divided according to GPU number during AutoTP, 3 GPUs may not work. It may be better that you use 2 or 4 GPU to run AutoTP, or you could refer to our pipeline parallel methods to use 3 GPU (https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Pipeline-Parallel-FastAPI, https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Pipeline-Parallel-Inference)
