### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by K-Alex13** [intel-analytics/ipex-llm#11159]
![image](https://github.com/intel-analytics/ipex-llm/assets/74948610/f4d25c60-4432-4642-83a3-7758ea7be8cd)

today I find this problem that I can not install this package even use the install method from intel web
please help me

**Comment by Oscilloscope98** [comment]
Hi @K-Alex13,

On windows, to install IPEX-LLM on Intel CPUs, you could use:

```cmd
conda create -n llm python=3.11
conda activate llm

pip install --pre --upgrade ipex-llm[all]
```

On windows, to install IPEX-LLM on Intel GPUs, you could use:

```cmd
conda create -n llm python=3.11 libuv
conda activate llm

pip install --pre --upgrade ipex-llm[xpu] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
```

Please refer to [here](https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install.html) regarding IPEX-LLM installation.

Please let us know for any further problems :)

**Comment by K-Alex13** [comment]
thankyou
