### ISSUE TITLE
bug for inference qwen1.5-7b-chat with SYM_INT4 on Windows platform

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#11162]
<img width="437" alt="a516933d8abbde70e8dfed057a3094a" src="https://github.com/intel-analytics/ipex-llm/assets/99886928/14977b78-55a0-4a2c-b339-e94e89d0af10">

**Comment by Fred-cell** [comment]
(llm) C:\Users\Intel\github\ipex-llm\python\llm\scripts>.\env-check.bat
Python 3.10.14
-----------------------------------------------------------------
transformers=4.37.0
-----------------------------------------------------------------
torch=2.1.0a0+git7bcf7da
-----------------------------------------------------------------
Name: ipex-llm
Version: 2.1.0b1
Summary: Large Language Model Develop Toolkit
Home-page: https://github.com/intel-analytics/BigDL
Author: BigDL Authors
Author-email: bigdl-user-group@googlegroups.com
License: Apache License, Version 2.0
Location: c:\users\intel\.conda\envs\llm\lib\site-packages
Requires:
Required-by:
-----------------------------------------------------------------
C:\Users\Intel\.conda\envs\llm\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\Intel\.conda\envs\llm\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
ipex=2.1.20+git4849f3b
-----------------------------------------------------------------
Total Memory: 31.696 GB

Chip 0 Memory: 16 GB | Speed: 4800 MHz
Chip 1 Memory: 16 GB | Speed: 4800 MHz
-----------------------------------------------------------------
CPU Manufacturer: GenuineIntel
CPU MaxClockSpeed: 2100
CPU Name: 12th Gen Intel(R) Core(TM) i7-12700
CPU NumberOfCores: 12
CPU NumberOfLogicalProcessors: 20
-----------------------------------------------------------------
GPU 0: Intel(R) UHD Graphics 770         Driver Version:  31.0.101.4953
-----------------------------------------------------------------
-----------------------------------------------------------------
System Information

主机名:           DESKTOP-7G6V8RU
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19045 暂缺 Build 19045
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     Intel
注册的组织:       暂缺
产品 ID:          00355-62748-44749-AAOEM
初始安装日期:     2023/3/29, 11:20:18
系统启动时间:     2024/5/28, 20:22:38
系统制造商:       Dell Inc.
系统型号:         Precision 3660
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 151 Stepping 2 GenuineIntel ~2100 Mhz
BIOS 版本:        Dell Inc. 2.14.0, 2024/4/9
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     32,457 MB
可用的物理内存:   11,583 MB
虚拟内存: 最大值: 37,577 MB
虚拟内存: 可用:   10,597 MB
虚拟内存: 使用中: 26,980 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\DESKTOP-7G6V8RU
修补程序:         安装了 14 个修补程序。
                  [01]: KB5037587
                  [02]: KB5037592
                  [03]: KB4534170
                  [04]: KB4537759
                  [05]: KB4545706
                  [06]: KB4598481
                  [07]: KB5011048
                  [08]: KB5011050
                  [09]: KB5012170
                  [10]: KB5015684
                  [11]: KB5033052
                  [12]: KB5037768
                  [13]: KB5020372
                  [14]: KB5037240
网卡:             安装了 2 个 NIC。
                  [01]: Intel(R) Ethernet Connection (17) I219-LM
                      连接名:      以太网
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.10.1
                      IP 地址
                        [01]: 192.168.10.2
                        [02]: fe80::9738:18f2:c2de:3e59
                  [02]: Hyper-V Virtual Ethernet Adapter
                      连接名:      vEthernet (WSL)
                      启用 DHCP:   否
                      IP 地址
                        [01]: 172.29.144.1
                        [02]: fe80::bbf6:2a37:e0fc:cb01
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。
-----------------------------------------------------------------
'xpu-smi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
xpu-smi is not installed properly.

(llm) C:\Users\Intel\github\ipex-llm\python\llm\scripts>

**Comment by lalalapotter** [comment]
Cannot reproduce the issue with [all-in-one benchmark](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/dev/benchmark/all-in-one), using 1k-512, qwen1.5-7b and sym_int4 precision. Could you please provide  detail config or running scripts for us to address the issue.

**Comment by hkvision** [comment]
From customer feedback from @Fred-cell : This happened once for the first request after the service is launched. After reloading the model, the issue disappears.

Will further track this if it still happens.
