### ISSUE TITLE
IPEX-LLM on Ultra 155H 

### ISSUE THREAD

**Issue by kylinzhao90** [intel-analytics/ipex-llm#11214]
Ultra 155H platform(https://ark.intel.com/content/www/us/en/ark/products/236847/intel-core-ultra-7-processor-155h-24m-cache-up-to-4-80-ghz.html). 
We installed Text Generation WebUI on Intel GPU according to https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Quickstart/webui_quickstart.html successfully. 
But after load model on iGPU and chat with AI, The entire output is meaningless text  as below.   Can you help have a look?
![image](https://github.com/intel-analytics/ipex-llm/assets/92354341/b1f2aba3-d7ae-4f39-b0cc-c9046a6bda1d)

As a comparison,  load with CPU, it works well as below.
![image](https://github.com/intel-analytics/ipex-llm/assets/92354341/9070a567-27ae-4e4c-bfee-0a496d3a3d71)

**Comment by sgwhat** [comment]
Hi @kylinzhao90 , which model are you running?

**Comment by kylinzhao90** [comment]
> Hi @kylinzhao90 , which model are you running?

TinyLlama/TinyLlama-1.1B-Chat-v1.0

**Comment by sgwhat** [comment]
Hi @kylinzhao90 , we are reproducing your issue and will inform you when we have made progress.

**Comment by sgwhat** [comment]
Hi @kylinzhao90 , I cannot reproduce your issue, may I know your `ipex-llm` and `transformers` version?

![image](https://github.com/intel-analytics/ipex-llm/assets/38711238/00fce966-298e-450c-bbb4-00f60cc1a6fe)

**Comment by kylinzhao90** [comment]
my test environment was deleted, please close this issue, I will ask for help if I encounter it again.
