### ISSUE TITLE
all-in-one based version 2.1.0b1 issue for llama3-8b-instruct with 128-2048

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#11212]
Last iterator is verfy slow for llama3-8b-instruct & fp8.

**Comment by lalalapotter** [comment]
Cannot reproduce the issue in the env provided by user, will sync details offline.

**Comment by lalalapotter** [comment]
After sync with user offline, cannot reproduce in users' env, will keep monitor similar behavior, close issue for now.
