### ISSUE TITLE
Ollama Linux seg fault with GPU on Ubuntu 22.04

### ISSUE THREAD

**Issue by doucej** [intel-analytics/ipex-llm#11269]
Ran into seg faults trying to run Ollama on Ubuntu 22.04. This is with an Intel Arc A750 card.

A few searches showed a similar finigerprint in https://github.com/intel/compute-runtime/issues/710. Reporting this as similar workaround of:

export NEOReadDebugKeys=1
export OverrideGpuAddressSpace=48

does the trick to get things working. Did a:
pip install --pre --upgrade ipex-llm[cpp]

just today, still not getting versions that have this fixed, so maybe coming soon, but wanted to raise failure fingerprint and workaround.

**Comment by sgwhat** [comment]
Hi @doucej , could you please provide more information from the ollama server side (like the ollama server log)? This would be helpful for us in addressing the issue and fixing it.

**Comment by sgwhat** [comment]
hi @doucej, this issue is due to oneAPI not being installed correctly. You may run ollama with following steps:

1. Please run `sycl-ls` to check your sycl devices. The expected output should be as below:
    ```bash
    [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  
    [2023.16.12.0.12_195853.xmain-hotfix]
    [opencl:cpu:1] Intel(R) OpenCL, Intel(R) Core(TM) Ultra 5 125H OpenCL 3.0 (Build 0) [2023.16.12.0.12_195853.xmain-hotfix]
    [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) Graphics OpenCL 3.0 NEO  [24.09.28717.12]
    [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) Graphics 1.3 [1.3.28717]
    ``` 
    If `[ext_oneapi_level_zero:gpu]` is not present, please proceed to step 2.

2. You may follow our guide to reinstall oneAPI: https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#id1.

**Comment by doucej** [comment]
Thanks -- yes, I do have my GPU listed:

```
(base) doucej@kryten:~$ source /opt/intel/oneapi/setvars.sh
 
:: initializing oneAPI environment ...
   bash: BASH_VERSION = 5.2.21(1)-release
   args: Using "$@" for setvars.sh arguments: 
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: ipp -- latest
:: ippcp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
 
(base) doucej@kryten:~$ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2024.17.3.0.08_160000]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz OpenCL 3.0 (Build 0) [2024.17.3.0.08_160000]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A750 Graphics OpenCL 3.0 NEO  [23.43.027642]
(base) doucej@kryten:~$ 
```

I did try creating a new conda environment today through:

```
conda create -n llm-cpp python=3.11
conda activate llm-cpp
pip install --pre --upgrade ipex-llm[cpp]
```

And followed through with deleting the old ollama binary and an init-ollama.

Back to the same point, need those extra environment variables for it to see/utilize the GPU without crashing.

When installing as above, do I also need to go through and install/update the oneapi packages through apt, or is above PIP getting that set up for me? I could try that if this still seems like a setup/installation issue.

Thanks!

**Comment by sgwhat** [comment]
Hi @doucej , this failure of Ollama to run is because you **haven't correctly installed OneAPI**. If you have installed OneAPI correctly, `[ext_oneapi_level_zero:gpu]` should be present as expected in the output of `sycl-ls`.  

To fix this issue, you may follow our guide to reinstall oneAPI: https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#id1.

Also, would you mind running https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts to check system environment and reply us the output?

**Comment by doucej** [comment]
Some notes below. I did go through and try to reinstall oneAPI, looks like indeed I had an old version on there from previous rev ubuntu most likely. 

Some notes:

Before touching anything, after activating llm-cpp conda, source /opt/intel/oneapi/setvars.sh:


```
(llm-cpp) doucej@kryten:~$ ~/Downloads/env-check.sh 
-----------------------------------------------------------------
PYTHON_VERSION=3.11.9
-----------------------------------------------------------------
transformers=4.41.2
-----------------------------------------------------------------
torch=2.2.0+cu121
-----------------------------------------------------------------
ipex-llm Version: 2.1.0b20240620
-----------------------------------------------------------------
IPEX is not installed. 
-----------------------------------------------------------------
CPU Information: 
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               44
On-line CPU(s) list:                  0-43
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz
CPU family:                           6
Model:                                79
Thread(s) per core:                   2
Core(s) per socket:                   22
Socket(s):                            1
Stepping:                             1
CPU(s) scaling MHz:                   55%
CPU max MHz:                          3700.0000
CPU min MHz:                          1200.0000
-----------------------------------------------------------------
Total CPU Memory: 39.0826 GB
-----------------------------------------------------------------
Operating System: 
Ubuntu 24.04 LTS \n \l

-----------------------------------------------------------------
Linux kryten 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
/home/doucej/Downloads/env-check.sh: line 148: xpu-smi: command not found
-----------------------------------------------------------------
/home/doucej/Downloads/env-check.sh: line 154: clinfo: command not found
-----------------------------------------------------------------
Driver related package version:
rc  intel-fw-gpu                                    2022.47.1+190                            all          Firmware package for Intel integrated and discrete GPUs
ii  intel-level-zero-gpu                            1.3.26241.33-647~22.04                   amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
-----------------------------------------------------------------
igpu not detected
-----------------------------------------------------------------
xpu-smi is not installed. Please install xpu-smi according to README.md
(llm-cpp) doucej@kryten:~$ 

```

after:

  wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null

echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list

sudo apt update

sudo apt install intel-oneapi-common-vars=2024.0.0-49406 \
  intel-oneapi-common-oneapi-vars=2024.0.0-49406 \
  intel-oneapi-diagnostics-utility=2024.0.0-49093 \
  intel-oneapi-compiler-dpcpp-cpp=2024.0.2-49895 \
  intel-oneapi-dpcpp-ct=2024.0.0-49381 \
  intel-oneapi-mkl=2024.0.0-49656 \
  intel-oneapi-mkl-devel=2024.0.0-49656 \
  intel-oneapi-mpi=2021.11.0-49493 \
  intel-oneapi-mpi-devel=2021.11.0-49493 \
  intel-oneapi-dal=2024.0.1-25 \
  intel-oneapi-dal-devel=2024.0.1-25 \
  intel-oneapi-ippcp=2021.9.1-5 \
  intel-oneapi-ippcp-devel=2021.9.1-5 \
  intel-oneapi-ipp=2021.10.1-13 \
  intel-oneapi-ipp-devel=2021.10.1-13 \
  intel-oneapi-tlt=2024.0.0-352 \
  intel-oneapi-ccl=2021.11.2-5 \
  intel-oneapi-ccl-devel=2021.11.2-5 \
  intel-oneapi-dnnl-devel=2024.0.0-49521 \
  intel-oneapi-dnnl=2024.0.0-49521 \
  intel-oneapi-tcm-1.0=1.0.0-435
    

Let apt upgrade a bunch of intel-oneapi packages after initial install & reboot for good measure:

```
(ollama) doucej@kryten:~$ ~/Downloads/env-check.sh 
-----------------------------------------------------------------
PYTHON_VERSION=3.11.9
-----------------------------------------------------------------
transformers=4.41.2
-----------------------------------------------------------------
torch=2.2.0+cu121
-----------------------------------------------------------------
ipex-llm Version: 2.1.0b20240624
-----------------------------------------------------------------
IPEX is not installed. 
-----------------------------------------------------------------
CPU Information: 
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               44
On-line CPU(s) list:                  0-43
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz
CPU family:                           6
Model:                                79
Thread(s) per core:                   2
Core(s) per socket:                   22
Socket(s):                            1
Stepping:                             1
CPU(s) scaling MHz:                   55%
CPU max MHz:                          3700.0000
CPU min MHz:                          1200.0000
-----------------------------------------------------------------
Total CPU Memory: 39.0826 GB
-----------------------------------------------------------------
Operating System: 
Ubuntu 24.04 LTS \n \l

-----------------------------------------------------------------
Linux kryten 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------
/home/doucej/Downloads/env-check.sh: line 148: xpu-smi: command not found
-----------------------------------------------------------------
/home/doucej/Downloads/env-check.sh: line 154: clinfo: command not found
-----------------------------------------------------------------
Driver related package version:
rc  intel-fw-gpu                                    2022.47.1+190                            all          Firmware package for Intel integrated and discrete GPUs
ii  intel-level-zero-gpu                            1.3.26241.33-647~22.04                   amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
-----------------------------------------------------------------
igpu not detected
-----------------------------------------------------------------
xpu-smi is not installed. Please install xpu-smi according to README.md
(ollama) doucej@kryten:~$ sycl-ls
[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz OpenCL 3.0 (Build 0) [2024.18.6.0.02_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A750 Graphics OpenCL 3.0 NEO  [23.43.027642]
(ollama) doucej@kryten:~$ 

```

Now even the setenvs I was doing to workaround before aren't helping, just seg faults trying to start up. Will take another look at my oneapi install, I'm guessing something's messed up there. Odd that it wanted to update a bunch of those immediately after installation, not sure if that's expected.

**Comment by doucej** [comment]
Realized the title was off, working with Ubuntu 24.04. I've still not been able to get a good OneAPI installation even after a clean reinstall. I was able to get Ollama running with Vulkan with the the changes in https://github.com/ollama/ollama/pull/5059#. So maybe operator error here, nonetheless, I'm up and running, so this issue is moot for me for now.
