### ISSUE TITLE
Can faster whisper run on Intel iGPU or Arc DGPU?

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/ipex-llm#11329]
model download from https://huggingface.co/Systran/faster-whisper-large-v3/tree/main
Can faster whisper run on Intel MTL iGPU or Arc DGPU?

the source code can run on CPU:
```
from faster_whisper import WhisperModel
model = WhisperModel("../faster-whisper-large-v3")
```
(1) if add model.to("xpu") , it will
AttributeError: 'WhisperModel' object has no attribute 'to'

(2) if use transformers API, it will
```
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq
processor = AutoProcessor.from_pretrained("path/faster-whisper-large-v3",trust_remote_code=True)
```
 
  File "C:\Users\sutai\.conda\envs\llm\Lib\site-packages\transformers\models\whisper\tokenization_whisper.py", line 300, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by MeouSker77** [comment]
`faster_whisper` uses `ctranslate2` to load and use model, while `ctranslate2` uses a custom model written by C++, it's not a pytorch model, so we can't use `to('xpu')` to move it to xpu. The only way to use xpu is to modify `ctraslate2`'s source code and recompile it, this is a bit complicated.

**Comment by KiwiHana** [comment]
Thanks！
