### ISSUE TITLE
error with loading 4bit saved LLava model on CPU

### ISSUE THREAD

**Issue by tsantra** [intel-analytics/ipex-llm#11342]
Hi,

I used the example from:
https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/CPU/PyTorch-Models/Model/llava 

and modified the generate.py to save the optimized model. 
model = optimize_model(model)
#Added these lines below in the generate.py

**_if SAVE_PATH :
  model.save_low_bit(save_path_model)
  tokenizer.save_pretrained(save_path_model)
  print(f"Model and tokenizer are saved to {save_path_model}")_**

Then Tried to load the saved model by modifying the generate.py:

if LOAD_PATH:
        print ("............loading load_path")
        tokenizer = AutoTokenizer.from_pretrained(
        load_path, use_fast=False)
        model = LlavaLlamaForCausalLM.from_pretrained(
        load_path, low_cpu_mem_usage=True, **kwargs)
        model = load_low_bit(model, load_path)

**_Getting error:_**
/LLaVA/./generate.py", line 309, in <module>
    tokenizer, model, image_processor, _ = load_pretrained_model(model_path=model_path,
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ceed-user/LLaVA/./generate.py", line 165, in load_pretrained_model
    model = load_low_bit(model, load_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ceed-user/miniforge3/envs/ipex-llm-cpu/lib/python3.11/site-packages/ipex_llm/optimize.py", line 193, in load_low_bit
    set_module_tensor_to_device(model, param_name, "cpu", param)
  File "/home/ceed-user/miniforge3/envs/ipex-llm-cpu/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 255, in set_module_tensor_to_device
    new_module = getattr(module, split)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ceed-user/miniforge3/envs/ipex-llm-cpu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CLIPVisionTower' object has no attribute 'vision_tower'. Did you mean: 'vision_tower_name'?

**_The modified function in generate.py to load 4bit llava model (highlighted in bold)_**

def load_pretrained_model(model_path, model_base, model_name, load_8bit=False, load_4bit=False,
                          device_map="auto", device="cpu"):
    kwargs = {"device_map": device_map}
    kwargs['torch_dtype'] = torch.float32

    if 'llava' in model_name.lower():
        # Load LLaVA model
        if 'lora' in model_name.lower() and model_base is None:
            warnings.warn('There is `lora` in model name but no `model_base` is provided.'
                          'If you are loading a LoRA model, please provide the `model_base` argument'
                          '. Detailed instruction:'
                          'https://github.com/haotian-liu/LLaVA#launch-a-model-worker-lora-weights-unmerged.')
        if 'lora' in model_name.lower() and model_base is not None:
            lora_cfg_pretrained = AutoConfig.from_pretrained(model_path)
            tokenizer = AutoTokenizer.from_pretrained(
                model_base, use_fast=False)
            print('Loading LLaVA from base model...')
            model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True,
                                                          config=lora_cfg_pretrained, **kwargs)
            token_num, tokem_dim = model.lm_head.out_features, model.lm_head.in_features
            if model.lm_head.weight.shape[0] != token_num:
                model.lm_head.weight = torch.nn.Parameter(torch.empty(
                    token_num, tokem_dim, device=model.device, dtype=model.dtype))
                model.model.embed_tokens.weight = torch.nn.Parameter(torch.empty(
                    token_num, tokem_dim, device=model.device, dtype=model.dtype))

            print('Loading additional LLaVA weights...')
            if os.path.exists(os.path.join(model_path, 'non_lora_trainables.bin')):
                non_lora_trainables = torch.load(os.path.join(model_path,
                                                              'non_lora_trainables.bin'),
                                                 map_location='cpu')
            else:
                # this is probably from HF Hub
                from huggingface_hub import hf_hub_download

                def load_from_hf(repo_id, filename, subfolder=None):
                    cache_file = hf_hub_download(
                        repo_id=repo_id,
                        filename=filename,
                        subfolder=subfolder)
                    return torch.load(cache_file, map_location='cpu')
                non_lora_trainables = load_from_hf(
                    model_path, 'non_lora_trainables.bin')
            non_lora_trainables = {(k[11:] if k.startswith(
                'base_model.') else k): v for k, v in non_lora_trainables.items()}
            if any(k.startswith('model.model.') for k in non_lora_trainables):
                non_lora_trainables = {(k[6:] if k.startswith(
                    'model.') else k): v for k, v in non_lora_trainables.items()}
            model.load_state_dict(non_lora_trainables, strict=False)

            from peft import PeftModel
            print('Loading LoRA weights...')
            model = PeftModel.from_pretrained(model, model_path)
            print('Merging LoRA weights...')
            model = model.merge_and_unload()
            print('Model is loaded...')
        elif model_base is not None:
            # this may be mm projector only
            print('........................Loading LLaVA from base model...')
            if 'mpt' in model_name.lower():
                if not os.path.isfile(os.path.join(model_path, 'configuration_mpt.py')):
                    shutil.copyfile(os.path.join(model_base, 'configuration_mpt.py'), os.path.join(
                        model_path, 'configuration_mpt.py'))
                tokenizer = AutoTokenizer.from_pretrained(
                    model_base, use_fast=True)
                cfg_pretrained = AutoConfig.from_pretrained(
                    model_path, trust_remote_code=True)
                model = LlavaMPTForCausalLM.from_pretrained(
                    model_base, low_cpu_mem_usage=True, config=cfg_pretrained, **kwargs)
            else:
                print (" ..................loading from here 1")
                tokenizer = AutoTokenizer.from_pretrained(
                    model_base, use_fast=False)
                cfg_pretrained = AutoConfig.from_pretrained(model_path)
                model = LlavaLlamaForCausalLM.from_pretrained(
                    model_base, low_cpu_mem_usage=True, config=cfg_pretrained, **kwargs)

            mm_projector_weights = torch.load(os.path.join(
                model_path, 'mm_projector.bin'), map_location='cpu')
            mm_projector_weights = {k: v.to(torch.float32)
                                    for k, v in mm_projector_weights.items()}
            model.load_state_dict(mm_projector_weights, strict=False)
        else:
            if 'mpt' in model_name.lower():
                tokenizer = AutoTokenizer.from_pretrained(
                    model_path, use_fast=True)
                model = LlavaMPTForCausalLM.from_pretrained(
                    model_path, low_cpu_mem_usage=True, **kwargs)
            else:
                **_if LOAD_PATH:
                    print ("............loading load_path")
                    tokenizer = AutoTokenizer.from_pretrained(
                    load_path, use_fast=False)
                    model = LlavaLlamaForCausalLM.from_pretrained(
                    load_path, low_cpu_mem_usage=True, **kwargs)
                    model = load_low_bit(model, load_path)_**
                else:           
                    
                    print (" ....................loading from here 2")
                    tokenizer = AutoTokenizer.from_pretrained(
                        model_path, use_fast=False)
                    model = LlavaLlamaForCausalLM.from_pretrained(
                        model_path, low_cpu_mem_usage=True, **kwargs)
    else:
        # Load language model
        if model_base is not None:
            # PEFT model
            from peft import PeftModel
            tokenizer = AutoTokenizer.from_pretrained(
                model_base, use_fast=False)
            model = AutoModelForCausalLM.from_pretrained(
                model_base, torch_dtype=torch.float32, low_cpu_mem_usage=True, device_map="auto")
            print(f"Loading LoRA weights from {model_path}")
            model = PeftModel.from_pretrained(model, model_path)
            print(f"Merging weights")
            model = model.merge_and_unload()
            print('Convert to FP32...')
            model.to(torch.float32)
        else:
            use_fast = False
            if 'mpt' in model_name.lower():
                tokenizer = AutoTokenizer.from_pretrained(
                    model_path, use_fast=True)
                model = AutoModelForCausalLM.from_pretrained(
                    model_path, low_cpu_mem_usage=True, trust_remote_code=True, **kwargs)
            else:
                tokenizer = AutoTokenizer.from_pretrained(
                    model_path, use_fast=False)
                model = AutoModelForCausalLM.from_pretrained(
                    model_path, low_cpu_mem_usage=True, **kwargs)

    image_processor = None

    if 'llava' in model_name.lower():
        mm_use_im_start_end = getattr(
            model.config, "mm_use_im_start_end", False)
        mm_use_im_patch_token = getattr(
            model.config, "mm_use_im_patch_token", True)
        if mm_use_im_patch_token:
            tokenizer.add_tokens(
                [DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)
        if mm_use_im_start_end:
            tokenizer.add_tokens(
                [DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN], special_tokens=True)
        model.resize_token_embeddings(len(tokenizer))

        vision_tower = model.get_vision_tower()
        if not vision_tower.is_loaded:
            vision_tower.load_model()
        vision_tower.to(device=device, dtype=torch.float32)
        image_processor = vision_tower.image_processor

    if hasattr(model.config, "max_sequence_length"):
        context_len = model.config.max_sequence_length
    else:
        context_len = 2048

    return tokenizer, model, image_processor, context_len

**What is the right way to load the 4bit saved model? I am using CPU.**

**Comment by JinBridger** [comment]
Hi, @tsantra!

Here is a function to load optimized LLaVA model on CPU. Maybe you could have a try?

```python
def load_low_bit_llava(load_path):
    tokenizer = AutoTokenizer.from_pretrained(load_path, use_fast=False)
    model = LlavaLlamaForCausalLM.from_pretrained(load_path, low_cpu_mem_usage=True, torch_dtype=torch.float32)

    mm_use_im_start_end = getattr(
        model.config, "mm_use_im_start_end", False)
    mm_use_im_patch_token = getattr(
        model.config, "mm_use_im_patch_token", True)
    if mm_use_im_patch_token:
        tokenizer.add_tokens(
            [DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)
    if mm_use_im_start_end:
        tokenizer.add_tokens(
            [DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN], special_tokens=True)

    vision_tower = model.get_vision_tower()
    if not vision_tower.is_loaded:
        vision_tower.load_model()
    model = load_low_bit(model, load_path)

    vision_tower.to(device="cpu", dtype=torch.float32)
    image_processor = vision_tower.image_processor

    if hasattr(model.config, "max_sequence_length"):
        context_len = model.config.max_sequence_length
    else:
        context_len = 2048

    return tokenizer, model, image_processor, context_len
```

Usage:

```python
tokenizer, model, image_processor, _ = load_low_bit_llava(load_path="PATH/TO/SAVED/MODEL")
```

Please feel free to ask if there's any problem :)

**Comment by tsantra** [comment]
Hi @JinBridger , this works for me. Thank you!

**Comment by Oscilloscope98** [comment]
Close this issue for now. Feel free reopen it if there are any further problems :)
