### ISSUE TITLE
is support Intel® Xeon® Gold 5220R Processor (2nd Generation Intel® Xeon® Scalable Processors, formerly Cascade Lake,)?

### ISSUE THREAD

**Issue by RichardFans** [intel-analytics/ipex-llm#11367]
is support Intel® Xeon® Gold 5220R Processor (2nd Generation Intel® Xeon® Scalable Processors, formerly Cascade Lake,)?

**Comment by qiyuangong** [comment]
Yes, it's supported. But we only have AVX2 and AVX512 Instructions on Xeon® Gold 5220R. So, the end-to-end performance is worse than that of the 3rd and 4th Generation Xeons (AMX and AVX512 VNNI).


https://www.intel.com/content/www/us/en/products/sku/199354/intel-xeon-gold-5220r-processor-35-75m-cache-2-20-ghz/specifications.html

**Comment by RichardFans** [comment]
thanks for your reply.
