### ISSUE TITLE
Run vLLM CPU benchmarking with BenchmarkWrapper API

### ISSUE THREAD

**Issue by eugeooi** [intel-analytics/ipex-llm#11522]
Is there a way to run vLLM CPU benchmarking with BenchmarkWrapper API? I have tried with [benchmark_vllm_throughput.py](https://github.com/intel-analytics/ipex-llm/blob/7cb09a8eac6747fc15054968559cd728431a9f9c/docker/llm/serving/cpu/docker/benchmark_vllm_throughput.py), but it doesn't profile First Token Latency and Second Token Latency.

**Comment by gc-fu** [comment]
Hi, the BenchmarkWrapper API does not support ``vLLM` models.  Besides, `benchmark_vllm_throughput.py` is not used for profiling token latencies.

For profiling token latencies, you can start a vllm sevice, and send requests to profile the token latencies.
