### ISSUE TITLE
Lightweight llm serving on win11 for iGPU of MTL

### ISSUE THREAD

**Issue by HoppeDeng** [intel-analytics/ipex-llm#11603]

**Comment by hzjane** [comment]
Now lightweight llm serving can be run [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Pipeline-Parallel-Serving#2-1-run-ipex-llm-serving-on-one-gpu-card). And more information and detailed guide will be added in this [PR](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Pipeline-Parallel-Serving)

**Comment by HoppeDeng** [comment]
@hzjane Thanks for your reply! Is there a guide for win11?

**Comment by hzjane** [comment]
Maybe you can refer to this [guide](https://github.com/intel-analytics/ipex-llm/blob/main/docs/readthedocs/source/doc/LLM/Quickstart/install_windows_gpu.md) to install related dependence on win11, and run Lightweight Serving using [this source code](https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/example/GPU/Pipeline-Parallel-Serving/serving.py) Now. We are verifying on win11 and will provide a more detailed readme later.
```bash
 set SYCL_CACHE_PERSISTENT=1
 set BIGDL_LLM_XMX_DISABLED=1
 python serving.py --repo-id-or-model-path $MODEL_PATH --low-bit $LOW_BIT
```

**Comment by HoppeDeng** [comment]
It can work now for both TGI and OpenAI API, thanks a lot!
