### ISSUE TITLE
gpu第一次以及放久了为什么每次询问都要初始化，影响返回值速度

### ISSUE THREAD

**Issue by dayskk** [intel-analytics/ipex-llm#11608]
gpu第一或者放5分钟以上，必现，用ollama问个问题，要等30多秒或20多秒才会答复，一旦又答复了以后，再进行问答，答复就很快，但是放个5分钟以上，再重新问，就要等20多秒或30多秒
![Uploading 微信图片_20240718090726.jpg…]()

**Comment by dayskk** [comment]
![微信图片_20240718090633](https://github.com/user-attachments/assets/c95bd407-0d2d-4311-959f-2d0d3427f9e7)
![微信图片_20240718090708](https://github.com/user-attachments/assets/e71d42de-65dd-47d2-b5da-8df223f7ef9d)
![微信图片_20240718090715](https://github.com/user-attachments/assets/9b95aa73-af4b-4562-b4e9-4388418989bd)
![微信图片_20240718090721](https://github.com/user-attachments/assets/ba54c162-666d-4aa3-80c5-5f8cc72c9d4d)
![Uploading 微信图片_20240718090726.jpg…]()

**Comment by biyuehuang** [comment]
可以把CPU和iGPU推理情况做一组对照试验，看看CPU是否存在同样的问题。因为用CPU推理时是原生的ollama。
把这个变量设成0，就是ollama在CPU上推理。
set OLLAMA_NUM_GPU=0

**Comment by dayskk** [comment]
cpu速度目前还比gpu快，当gpu第一次或间隔5分钟后再问答
cpu很均衡，都是5，6秒就答复上来了

**Comment by dayskk** [comment]
gpu第一次或间隔5分钟后，再问答，回答回来速度是20多秒或30多秒

**Comment by biyuehuang** [comment]
ollama 模型放iGPU的时候，5分钟后，任务管理器可以看到模型已经不在iGPU内存里了。需求是修改成模型一直留在iGPU，不被释放，以减少ollama静止5分钟后对话的等待时间

**Comment by rnwang04** [comment]
Ollama will unload model from gpu memory in every 5 minutes as default.
For latest version of ollama, you could `set OLLAMA_KEEP_ALIVE=-1` to keep the model loaded in memory.

**Comment by biyuehuang** [comment]
The customer has verified that ”set OLLAMA_KEEP_ALIVE=-1“ was OK
