### ISSUE TITLE
Cannot run Gemma2 on Ollama with ipex-llm

### ISSUE THREAD

**Issue by mouse33333** [intel-analytics/ipex-llm#11627]
Hi 

I can run Llama3, Qwen or other models on Ollama with ipex-llm. However, I cannot run Gemm2 on Ollama with ipex-llm. It shows unknown model architecture: 'gemma2'. Does it mean this model is not supported by ipex-llma?

Here're the details:
![screenshot-20240722-101506](https://github.com/user-attachments/assets/de6f2f65-269e-4106-9298-58758853a078)

Thank you for your help in advance~

**Comment by sunnsi** [comment]
+1. Please update the supported version of Ollama. The current version is 0.2.7, however, Ipex-LLM only supports up to 0.1.39."

**Comment by rollinsjw** [comment]
Also love this idea, enjoying running models locally and would love to play with deepseekv2 and gemma2

**Comment by rnwang04** [comment]
Hi all, Gemma2 is supported with `ipex-llm[cpp] >= 2.1.0b20240724`, you may try it again : )

**Comment by mouse33333** [comment]
> Hi all, Gemma2 is supported with `ipex-llm[cpp] >= 2.1.0b20240724`, you may try it again : )

It works now! Thank you for your support!
