### ISSUE TITLE
[Windows][codegeex4-all-9B] deployment fail

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/ipex-llm#11634]
use https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Lightweight-Serving to deploy codegeex4-all-9B as VS code plug in 

Configure: http://localhost:8000/v1/chat/completions
INFO:     127.0.0.1:9542 - "OPTIONS /v1/chat/completions HTTP/1.1" 405 Method Not Allowed

**Comment by hzjane** [comment]
This error may be caused by missing `OPTIONS method` required by the plugin., you can add this code below [here](https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/src/ipex_llm/serving/fastapi/api_server.py#L56) to test.
```bash
from fastapi.middleware.cors import CORSMiddleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
```

**Comment by juan-OY** [comment]
thanks, issue is resolved
