### ISSUE TITLE
Recipe for loading a Low-bit Safetensors Model?

### ISSUE THREAD

**Issue by akashaero** [intel-analytics/ipex-llm#11651]
Hello,

I have converted Llama-3.1-8B model to FP8 using IPEX-LLM and then converted model weights from .bin files to Safetensors file on HuggingFace.

I am not able to load low bit safetensors model using IPEX-LLM `load_low_bit` method. It complains about not being able to find .bin files. 

Is there a way to load low bit models stored in Safetensors format?

Thanks,

**Comment by leonardozcm** [comment]
Hi @akashaero , for now we **only** support save low bit weights with pytorch `.bin` format and load low bit weights in `.bin`, `.safetensor` is not in our scope for now.

**Comment by akashaero** [comment]
Fair enough.

I was thinking that since the `AutoModelForCausalLM.from_pretrained` method loads Safetensors, can I tweak the `config.json` of a low_bit converted model to remove the "low_bit" keyword and trick the model loading pipeline into believing that the model is not the low bit model?

Let me know if this could work!

Thanks

**Comment by leonardozcm** [comment]
hi, I am sorry that I think this is not working either, this may lead to missing of our optimization.

**Comment by akashaero** [comment]
Thanks for your answers! I will close this issue now.
