### ISSUE TITLE
Can we support InternVL2-4B?

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/ipex-llm#11670]
New model support request on MTL:

https://huggingface.co/OpenGVLab/InternVL2-4B

**Comment by notsyncing** [comment]
Hello, InternVL2 already works on ipex-llm (2.1.0b20240719) according to my tests with InternVL2-8B on A770 16GB, around 15~17 token/s with `load_in_4bit`.

btw, will we get any performance improvement on this model? like ~40t/s on qwen2 on my A770

**Comment by MeouSker77** [comment]
Supported in latest ipex-llm
