### ISSUE TITLE
[MTL][Internvl2-4B] GPU OOM for 3k input tokens

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/ipex-llm#11745]
Running Internvl2-4B, 

input token: 1024; Mem: 4.69GB
input token:2048;Mem: 9.3 GB
input token:3096 Mem: OOM

everything looks to be ok when input token is less or equal to 1k, but from 1k to 2k, GPU memory almost doubles, and it leads to OOM at 3K input tokens.

**Comment by hzjane** [comment]
I can't reproduce this issue. I use low_bit fp8 to generate 128 output tokens with model [Internvl2-4B](https://huggingface.co/OpenGVLab/InternVL2-4B/tree/main) on mtl. My Result:

model_load Mem: 4.5GB
input token: 1024; Mem: 5.425 GB
input token:2048; Mem: 6.291015625 GB
input token:3096; Mem: 8.302734375 GB

 Can you provide the detailed code and scripts？
