### ISSUE TITLE
Lightweight-serving support for codegeex is broken

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/ipex-llm#11757]
It reports below error:

File "C:\Users\MTL\AppData\Local\miniforge3\envs\codegeex\Lib\site-packages\ipex_llm\serving\fastapi\api_server.py", line 337, in create_chat_completion
    prompt, image_list = get_prompt(request.messages)
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
INFO:     127.0.0.1:59708 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

**Comment by hzjane** [comment]
Thanks for your issue. This issue will be fixed by this [PR](https://github.com/intel-analytics/ipex-llm/pull/11759/files).

**Comment by juan-OY** [comment]
Yes, the issue is resolved
