### ISSUE TITLE
GPU memory continue increase when in Deepspeed TP benchmark 

### ISSUE THREAD

**Issue by oldmikeyang** [intel-analytics/ipex-llm#11764]
GPU memory usage continue increase when run Deepspeed TP benchmark on 4 ARC GPU.
Qwen1.5-14B-Chat with sys_int4
Will cause out of memory in the latest test.

![err1](https://github.com/user-attachments/assets/ebfdc342-e7f1-44a8-b1bd-aa080a2c159e)
![err2](https://github.com/user-attachments/assets/f0f6266a-9d8c-453c-ae5b-deba27d5d012)

**Comment by Uxito-Ada** [comment]
Hi @oldmikeyang , could you share your `config.yaml` file under all-in-one directory, as configurations e.g. in_out_pairs and batch_size also influence the memory consumption. We will then try to reproduce your issue.

**Comment by oldmikeyang** [comment]
Resolve this issue after set the following ENV.
Please close this issue.

export IPEX_LLM_QUANTIZE_KV_CACHE=1
export IPEX_LLM_LOW_MEM=1

**Comment by oldmikeyang** [comment]
Resolve this issue after set the following ENV.

export IPEX_LLM_QUANTIZE_KV_CACHE=1
export IPEX_LLM_LOW_MEM=1
