### ISSUE TITLE
ollama runs gemma:2b, asks a question, does not answer, and reports no error.

### ISSUE THREAD

**Issue by Jieszs** [intel-analytics/ipex-llm#11771]
设备：intel n97
内存：8gb
ipex-llm版本:0811
现象：能够正常加载并运行gemma:2b,但是提问没有回答，也没有报错信息。
如果是使用qwen2:1.5b是能够正常回答的。
![99dd79b9f5f5e8d2df0d5543cf29965](https://github.com/user-attachments/assets/47504fb7-2a73-470c-8b81-858660e6dae7)

**Comment by rnwang04** [comment]
Hi @Jieszs ,
I have reproduced this issue, and this issue seems be caused by current version of ipex-llm ollama has something wrong with gemma2:2b's default template.
Below is a workaround for gemma2:2b:
```
# Modelfile
FROM gemma2:2b
template """<start_of_turn>user
{{ if .System }}{{ .System }} {{ end }}{{ .Prompt }}<end_of_turn>
<start_of_turn>model
{{ .Response }}<end_of_turn>"""
```
```bash
ollama create mygemma2-2b -f Modelfile
ollama run mygemma2-2b
```
![image](https://github.com/user-attachments/assets/d6fc1f10-5c31-4630-8c0b-9705367d2116)

**Comment by Jieszs** [comment]
Thanks,it works
