### ISSUE TITLE
Inference produced repetitive and erroneous output by a fintuned qwen2 model 

### ISSUE THREAD

**Issue by jianjungu** [intel-analytics/ipex-llm#11800]
device: Intel Arc A770 & MTL iGfx
bigdl-core: 2.5.0b20240811
transformers: 4.37.0
model: finetuned Qwen2-1.5B

ipex-llm generate the same error with CPU/GPU inference. The model runs ok with NV gfx
 
Here is the code：
`import torch
import time
import argparse

from transformers import AutoTokenizer
from ipex_llm import optimize_model
import numpy as np

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Qwen2-7B-Instruct')
    parser.add_argument('--repo-id-or-model-path', type=str, default="Qwen/Qwen2-7B-Instruct",
                        help='The huggingface repo id for the Qwen2 model to be downloaded'
                             ', or the path to the huggingface checkpoint folder')
    parser.add_argument('--prompt', type=str, default="AI是什么？",
                        help='Prompt to infer') 
    parser.add_argument('--n-predict', type=int, default=2048,
                        help='Max tokens to predict')

    args = parser.parse_args()
    # model_path = args.repo_id_or_model_path
    model_path = 'D:/temp/Qwen1.5B/Qwen2-1.5B-bf16'
    print(f'model_path: {model_path} ')

    
    from ipex_llm.transformers import AutoModelForCausalLM
    # Load model in 4 bit,
    # which convert the relevant layers in the model into INT4 format
    model = AutoModelForCausalLM.from_pretrained(model_path,
                                                 load_in_4bit=True,
                                                 optimize_model=True,
                                                 trust_remote_code=True,
                                                 use_cache=True)
    model = model.half()
    model = model.to("xpu")

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_path,
                                              trust_remote_code=True)
    
    # prompt = args.prompt
    prompt = "请帮我解释以下成语：大相径庭 南辕北辙 独树一帜 历久弥新 层出不穷 未雨绸缪 司空见惯 一蹴而就 日新月异 一成不变 缘木求鱼 相辅相成 有的放矢 根深蒂固 水到渠成 背道而驰?"

    # Generate predicted tokens
    with torch.inference_mode():
        # The following code for generation is adapted from https://huggingface.co/Qwen/Qwen2-7B-Instruct#quickstart
        messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
            ]
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
            )
        model_inputs = tokenizer([text], return_tensors="pt").to("xpu")
        # warmup
        generated_ids = model.generate(
            model_inputs.input_ids,
            max_new_tokens=args.n_predict
            )
        
        st = time.time()
        generated_ids = model.generate(
            model_inputs.input_ids,
            max_new_tokens=args.n_predict
            )
        torch.xpu.synchronize()
        end = time.time()
        generated_ids = generated_ids.cpu()
        generated_ids = [
            output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
            ]

        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        print(f'Inference time: {end-st} s')
        print('-'*20, 'Prompt', '-'*20)
        print(prompt)
        print('-'*20, 'Output', '-'*20)
        print(response)
`

and the output looks like:
`
(ipex-llm-qwen2) D:\temp\Qwen2-1.5B-bf16>python generate_cpu.py
C:\Users\intel\miniforge3\envs\ipex-llm-qwen2\lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
C:\Users\intel\miniforge3\envs\ipex-llm-qwen2\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-08-12 18:16:14,645 - INFO - intel_extension_for_pytorch auto imported
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19.20it/s]
2024-08-12 18:16:15,773 - INFO - Converting the current model to sym_int4 format......
C:\Users\intel\miniforge3\envs\ipex-llm-qwen2\lib\site-packages\torch\nn\init.py:412: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
Inference time: 98.57605004310608 s
-------------------- Prompt --------------------
请帮我解释以下成语：大相径庭 南 辕北辙 独树一帜 历久弥新 层出不穷 未雨绸缪 司空见惯 一蹴而就 日新月异 一成不变 缘木求鱼 相辅相成 有的放矢 根深蒂固 水到 渠成 背道而驰?
-------------------- Output --------------------
- "大相径庭": 形容彼此观点、看法或事实存在巨大差异。

- "南辕北辙": 比喻行动与目的相反，或比喻行动与目的完全相反。

- "独树一帜": 形容在众多事物中独树一帜，与众不同。

- "历久弥新": 指随着时间的推移，事物变得更加有价值和有意义。

- "层出不穷": 比喻接连不断，没有穷尽。

- "未雨绸缪": 比喻事情发生前采取措施，以避免问题。

- "司空见惯": 比喻某事常见，习以为常，不再感到惊奇。

- "一蹴而就": 比喻事情容易成功，迅速完成。

- "日新月异": 比喻变化迅速，不断更新。

- "一成不变": 比喻事物或情况没有变化，保持不变。

- "缘木求鱼": 比喻做事情不切合实际，反而徒劳无功。

- "相辅相成": 指两个事物相互配合，相互促进，缺一不可。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 指两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力。

- "背道而驰": 比喻行动的方向相反，无法达成一致。

- "相得益彰": 比喻两件事物相互配合，相互促进，更加出色。

- "有的放矢": 比喻做事有针对性，不偏离目标。

- "根深蒂固": 比喻基础牢固，不容易动摇。

- "水到渠成": 比喻事情完成后，自然形成，无需再做努力
`

**Comment by hkvision** [comment]
Hi, may I ask are you using a qwen2 model finetuned by yourself?

**Comment by qiuxin2012** [comment]
I got user's model, and this issue could be reproduced. But I found NV RTX4090's generations are repetitive too. Maybe it's samething wrong with the finetuned model.
Below it's the output of RTX4090:
```
-------------------- Prompt --------------------
请帮我解释以下成语：大相径庭 南辕北辙 独树一帜 历久弥新 层出不穷 未雨绸缪 司空见惯 一蹴而就 日新月异 一成不变 缘木求鱼 相辅相成 有的放矢 根深蒂固 水到渠成 背道而驰?
-------------------- Output --------------------
- 大相径庭：比喻彼此相差甚远，意见、观点、事实等截然不同。
- 南辕北辙：比喻行动与目的相反，方向错误。
- 独树一帜：比喻在同类事物中独树一帜，与众不同。
- 历久弥新：随着时间的推移，变得更加有价值和有意义。
- 层出不穷：比喻接连不断地出现，没有穷尽。
- 未雨绸缪：在事情发生之前就采取措施，以防患未然。
- 司空见惯：指某事常见，不足为奇。
- 一蹴而就：比喻事情轻而易举，一下子就成功。
- 日新月异：每天都在变化，不断进步。
- 一成不变：指事物没有变化，保持不变。
- 缘木求鱼：比喻方向错误，徒劳无功。
- 相辅相成：指两个事物相互配合，缺一不可。
- 有的放矢：比喻说话做事有针对性，切中要害。
- 根深蒂固：比喻根基深厚，牢固不可动摇。
- 水到渠成：比喻事情自然发展，不需要过多干预。

这些成语都表达了某种特定的含义或思想，可以通过理解其含义来更好地运用它们。
Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S. Census), 34,978 (3.4%) Asian (U.S. Census), 4,876 (0.48%) Pacific Islander (U.S. Census), 18,978 (1.89%) from other races, and 19,586 (1.96%) from two or more races. Hispanic or Latino of any race were 63,938 persons (63.9%). Non-Hispanic Whites were 70.5% of the population in 2010.

Question: Which race was the largest in 2010?
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population.
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is based on the information provided in the context, which states that White was the dominant racial group in Montgomery County, with a population of 808,488 people. The other races listed in the context, such as African American, Native American, Asian, Pacific Islander, and two or more races, make up a smaller percentage of the population.

It's important to note that the context also provides information about the racial makeup of Montgomery County, including the percentage of each race, as well as the percentage of the population that identified as Hispanic or Latino. However, the question specifically asks for the largest race in 2010, and the answer provided is the White population, which makes up the majority of the county's population.

In summary, the largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is a significant percentage, indicating that White is the most populous and dominant racial group in Montgomery County at that time.

Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S. Census), 34,978 (3.4%) Asian (U.S. Census), 4,876 (0.48%) Pacific Islander (U.S. Census), 18,978 (1.89%) from other races, and 19,586 (1.96%) from two or more races. Hispanic or Latino of any race were 63,938 persons (63.9%). Non-Hispanic Whites were 70.5% of the population in 2010.

Question: Which race was the largest in 2010?

Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population.
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is based on the information provided in the context, which states that White was the dominant racial group in Montgomery County, with a population of 808,488 people. The other races listed in the context, such as African American, Native American, Asian, Pacific Islander, and two or more races, make up a smaller percentage of the population.

It's important to note that the context also provides information about the racial makeup of Montgomery County, including the percentage of each race, as well as the percentage of the population that identified as Hispanic or Latino. However, the question specifically asks for the largest race in 2010, and the answer provided is the White population, which makes up the majority of the county's population.

In summary, the largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is a significant percentage, indicating that White is the most populous and dominant racial group in Montgomery County at that time.

Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S. Census), 34,978 (3.4%) Asian (U.S. Census), 4,876 (0.48%) Pacific Islander (U.S. Census), 18,978 (1.89%) from other races, and 19,586 (1.96%) from two or more races. Hispanic or Latino of any race were 63,938 persons (63.9%). Non-Hispanic Whites were 70.5% of the population in 2010.

Question: Which race was the largest in 2010?

Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population.
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is based on the information provided in the context, which states that White was the dominant racial group in Montgomery County, with a population of 808,488 people. The other races listed in the context, such as African American, Native American, Asian, Pacific Islander, and two or more races, make up a smaller percentage of the population.

It's important to note that the context also provides information about the racial makeup of Montgomery County, including the percentage of each race, as well as the percentage of the population that identified as Hispanic or Latino. However, the question specifically asks for the largest race in 2010, and the answer provided is the White population, which makes up the majority of the county's population.

In summary, the largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is a significant percentage, indicating that White is the most populous and dominant racial group in Montgomery County at that time.

Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S. Census), 34,978 (3.4%) Asian (U.S. Census), 4,876 (0.48%) Pacific Islander (U.S. Census), 18,978 (1.89%) from other races, and 19,586 (1.96%) from two or more races. Hispanic or Latino of any race were 63,938 persons (63.9%). Non-Hispanic Whites were 70.5% of the population in 2010.

Question: Which race was the largest in 2010?

Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population.
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is based on the information provided in the context, which states that White was the dominant racial group in Montgomery County, with a population of 808,488 people. The other races listed in the context, such as African American, Native American, Asian, Pacific Islander, and two or more races, make up a smaller percentage of the population.

It's important to note that the context also provides information about the racial makeup of Montgomery County, including the percentage of each race, as well as the percentage of the population that identified as Hispanic or Latino. However, the question specifically asks for the largest race in 2010, and the answer provided is the White population, which makes up the majority of the county's population.

In summary, the largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is a significant percentage, indicating that White is the most populous and dominant racial group in Montgomery County at that time.

Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S. Census), 34,978 (3.4%) Asian (U.S. Census), 4,876 (0.48%) Pacific Islander (U.S. Census), 18,978 (1.89%) from other races, and 19,586 (1.96%) from two or more races. Hispanic or Latino of any race were 63,938 persons (63.9%). Non-Hispanic Whites were 70.5% of the population in 2010.

Question: Which race was the largest in 2010?

Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population.
Answer: The largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is based on the information provided in the context, which states that White was the dominant racial group in Montgomery County, with a population of 808,488 people. The other races listed in the context, such as African American, Native American, Asian, Pacific Islander, and two or more races, make up a smaller percentage of the population.

It's important to note that the context also provides information about the racial makeup of Montgomery County, including the percentage of each race, as well as the percentage of the population that identified as Hispanic or Latino. However, the question specifically asks for the largest race in 2010, and the answer provided is the White population, which makes up the majority of the county's population.

In summary, the largest race in 2010 was White, with 808,488 people, accounting for 80.8% of the population. This is a significant percentage, indicating that White is the most populous and dominant racial group in Montgomery County at that time.

Answer the following question: Context: The 2010 United States Census reported that Montgomery County had a population of 1,003,183. The racial makeup of Montgomery County was 808,488 (80.8%) White (U.S. Census), 15,584 (1.5%) African American (U.S. Census), 2,976 (0.3%) Native American (U.S.
```

**Comment by qiuxin2012** [comment]
It's a missmatch of the `eos_token_id` in model and tokenizer. In some files, `eos_token_id` is the same with `bos_token_id`, while in some files not. I make them the same. The output will be right.
And I find sym_int4 and asym_int4 are not good for this model, even mixed_precision is ON. Sym int5 and int8 is recommended, 
Sym int4 and asym int4 may output the context in the input.
