### ISSUE TITLE
Qwen1.5-14B-Chat 支持问题，返回空

### ISSUE THREAD

**Issue by shabooboo86** [intel-analytics/ipex-llm#11833]
启动 Qwen1.5-14B-Chat 模型后，请求 completions 进行测试时，出现返回空的情况。
![image](https://github.com/user-attachments/assets/4ffc8eb7-754f-4aba-aaeb-6b852856bb77)
![image](https://github.com/user-attachments/assets/a94573e9-0184-489d-999a-17c9c756b48f)

**Comment by hzjane** [comment]
![image](https://github.com/user-attachments/assets/a57f4ee0-a54d-427b-b5af-e26cfd489528)
I can't reproduce this issue. I think it was caused by the streaming response. Maybe you can set the config `stream` = False to test
