### ISSUE TITLE
Error: 'wrong number of tensors; expected 292, got 291'

### ISSUE THREAD

**Issue by timroster** [intel-analytics/ipex-llm#11836]
Trying out the current versions of ipex-llm with `ollama` and when trying to use the `llama3.1` model the following output is displayed:

```
detect 1 SYCL GPUs: [0] with top Max compute units:512
llm_load_tensors: ggml ctx size =    0.30 MiB
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291
llama_load_model_from_file: exception loading model
terminate called after throwing an instance of 'std::runtime_error'
  what():  done_getting_tensors: wrong number of tensors; expected 292, got 291
time=2024-08-18T19:30:54.756Z level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: signal: aborted (core dumped) "
[GIN] 2024/08/18 - 19:30:54 | 500 |  1.820496414s |       127.0.0.1 | POST     "/api/chat"
```

This error looks like an exact match of: https://github.com/abetlen/llama-cpp-python/issues/1646 . Is it possible that there needs to be an update to the `llama-cpp-python` or just `llama.cpp` components included when doing `pip install --pre --upgrade ipex-llm[cpp]` from the [Quickstart guide](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md#1-install-ipex-llm-for-llamacpp)?

`ollama run llama3:8b-instruct-q4_K_M` working fine here. Platform is linux kernel 6.5 and ARC a770 GPU.

**Comment by rnwang04** [comment]
Hi @timroster ,
I have reproduced this error, and I will try to fix it later. Once it is done, will update here to let you know.

**Comment by rnwang04** [comment]
Llama 3.1 is supported with `ipex-llm[cpp] >= 2.1.0b20240819`, you may try it again tomorrow : )

**Comment by timroster** [comment]
@rnwang04 - I update the `ipex-llm` to `ipex-llm-2.1.0b20240819` version and it is working great. Thanks so much for the prompt response 😄

**Comment by Rishita32** [comment]
> @rnwang04 - I update the `ipex-llm` to `ipex-llm-2.1.0b20240819` version and it is working great. Thanks so much for the prompt response 😄

How do we update ipex-llm? Is it in convert_hf_to_gguf_update.py file?
