### ISSUE TITLE
Does ipex llm support the LLaMA 3.1 model?

### ISSUE THREAD

**Issue by JerryXu2023** [intel-analytics/ipex-llm#11844]
Does ipex llm support the LLaMA 3.1 model?
i try to run LLaMA 3.1 failed.

**Comment by rnwang04** [comment]
Hi @JerryXu2023 , do you want to run LLaMA 3.1 with ipex-llm[cpp] or ipex-llm[xpu] ?

**Comment by rnwang04** [comment]
If you mean ipex-llm[cpp], Llama 3.1 is supported with `ipex-llm[cpp] >= 2.1.0b20240819`, you may try it again tomorrow : )

**Comment by JerryXu2023** [comment]
Hi @rnwang04 
I want to run llama3.1 with cpp.
i will update to >= 2.1.0b20240819 and try again.
Thanks for you reply soon

**Comment by JerryXu2023** [comment]
Hi @rnwang04 
It's work fine now.Thanks
