### ISSUE TITLE
An exception occurred while installing llama.cpp

### ISSUE THREAD

**Issue by brownplayer** [intel-analytics/ipex-llm#11857]
Create llama. Unable to initialize llama after cpp folder. The cpp. bat

**Comment by ch1y0q** [comment]
Hi @brownplayer , could you please kindly provide some more information including your OS, commands for reproducing this issue, logs/screenshots of the error message, and anything that you believe might be helpful?

There are some common causes for the issue. For example, you have to be in an activated conda environment with `ipex-llm[cpp]` installed, to execute `init-llama-cpp`. Also, make sure you run Miniforge Prompt as administrator, in case you are using Windows.

For more details, please refer to https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md#2-setup-for-running-llamacpp.

**Comment by brownplayer** [comment]
thank for you help

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/20/2024 12:45 |
| To | intel-analytics/ipex-llm ***@***.***> |
| Cc | brownplayer ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [intel-analytics/ipex-llm] An exception occurred while installing llama.cpp (Issue #11857) |

Hi @brownplayer , could you please kindly provide some more information including your OS, commands for reproducing this issue, logs/screenshots of the error message, and anything that you believe might be helpful?

There are some common causes for the issue. For example, you have to be in an activated conda environment with ipex-llm[cpp] installed, to execute init-llama-cpp. Also, make sure you run Miniforge Prompt as administrator, in case you are using Windows.

For more details, please refer to https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md#2-setup-for-running-llamacpp.

**Comment by rnwang04** [comment]
@ch1y0q  Let's also add this issue into llama.cpp / ollama's trouble shooting section.

**Comment by brownplayer** [comment]
OK，Thank you for your service😄

---- Replied Message ----
| From | Ruonan ***@***.***> |
| Date | 08/20/2024 15:45 |
| To | intel-analytics/ipex-llm ***@***.***> |
| Cc | brownplayer ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [intel-analytics/ipex-llm] An exception occurred while installing llama.cpp (Issue #11857) |

@ch1y0q Let's also add this issue into llama.cpp / ollama's trouble shooting section.
