### ISSUE TITLE
May I ask how to pull the gptq format model that has been downloaded for the first time the second time?

### ISSUE THREAD

**Issue by brownplayer** [intel-analytics/ipex-llm#11870]
I downloaded the model in GPTQ format for the first time (ChenMnZ/ Mistral-large-instruction-2407-efficientqat-W2G64-GPTQ) by following the "save and load" section of the homepage. How can I use the first pulled model after I shut down the computer and restart it?

**Comment by brownplayer** [comment]
OK，thank you for your reply

---- Replied Message ----
| From | Yuwen ***@***.***> |
| Date | 08/21/2024 11:13 |
| To | intel-analytics/ipex-llm ***@***.***> |
| Cc | brownplayer ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [intel-analytics/ipex-llm] May I ask how to pull the gptq format model that has been downloaded for the first time the second time? (Issue #11870) |

Hi @brownplayer,

By default, Hugging Face model loaded the 1st time by repo id will be downloaded into HF_HOME folder, which is default to be ~/.cache/huggingface on Linux and C:\Users\your_user_name\.cache\huggingface on Windows.

The next time when you load the model by the same repo id, it should be loaded from HF_HOME automatically.

You could also set environment variable HF_HOME to the folder path to which you want the model to be downloaded.

Please let us know for any further problems :)

**Comment by hkvision** [comment]
Closing this issue. Feel free to tell us if you have further questions!
