### ISSUE TITLE
re-run init-llama-cpp will cause file exist

### ISSUE THREAD

**Issue by kevin-t-tang** [intel-analytics/ipex-llm#11893]
in the same folder and if old links broken, I want to re init llama cpp but got file exist,
seems the soft link cannot be overrride, please help. /-f

(llm-cpp) ubuntu@A $ ls
baby-llama     convert-hf-to-gguf.py  gguf-py              llama.log                lookup          perplexity      save-load-state  ubuntu
batched        convert.py             imatrix              llama.yetanotherlog.log  ls-sycl-device  quantize        server
batched-bench  embedding              llama_autonamed.log  llava-cli                main            quantize-stats  speculative
benchmark      gguf                   llama-bench          lookahead                main.log        run.bat         tokenize
(llm-cpp) ubuntu@A $ init-llama-cpp
ln: failed to create symbolic link './batched': File exists
ln: failed to create symbolic link './quantize': File exists
ln: failed to create symbolic link './llava-cli': File exists
ln: failed to create symbolic link './gguf': File exists
ln: failed to create symbolic link './perplexity': File exists
ln: failed to create symbolic link './main': File exists
ln: failed to create symbolic link './speculative': File exists
ln: failed to create symbolic link './tokenize': File exists
ln: failed to create symbolic link './llama-bench': File exists
ln: failed to create symbolic link './quantize-stats': File exists
ln: failed to create symbolic link './lookahead': File exists
ln: failed to create symbolic link './benchmark': File exists
ln: failed to create symbolic link './baby-llama': File exists
ln: failed to create symbolic link './imatrix': File exists
ln: failed to create symbolic link './embedding': File exists
ln: failed to create symbolic link './server': File exists
ln: failed to create symbolic link './batched-bench': File exists
ln: failed to create symbolic link './ls-sycl-device': File exists
ln: failed to create symbolic link './lookup': File exists
ln: failed to create symbolic link './save-load-state': File exists

**Comment by JinheTang** [comment]
Hi @kevin-t-tang, we will take a look at this request. Once it's done, we will update here to let you know.

**Comment by JinheTang** [comment]
Hi @kevin-t-tang , we have already covered this issue in our latest version. With `ipex-llm[cpp]>=2.2.0b20240827`, running `init-llama-cpp` and `init-ollama` will forcefully recreate all the symbolic links.
