### ISSUE TITLE
The open-webui fails to be started

### ISSUE THREAD

**Issue by brownplayer** [intel-analytics/ipex-llm#11902]
Displays after I type start start_windows.bat
![屏幕截图 2024-08-22 232759](https://github.com/user-attachments/assets/e72d78f5-dfc0-465d-8fae-47f1df45ec23)
![屏幕截图 2024-08-22 232822](https://github.com/user-attachments/assets/b630218a-8591-41d4-b026-32031aeadff0)
![image](https://github.com/user-attachments/assets/c597c335-352e-424c-971a-20da797f049c)
![image](https://github.com/user-attachments/assets/f67f68b2-77a1-4216-805a-d70ff0b1c83c)

**Comment by sgwhat** [comment]
Hi @brownplayer , could you show the versions of the dependencies you have installed to run open-webui (the result displayed by pip list)? Also, you may refer to [ipex-llm open-webui quickstart](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/open_webui_with_ollama_quickstart.md) to prepare your env.

**Comment by brownplayer** [comment]
of course
accelerate                               0.21.0
aiohappyeyeballs                         2.4.0
aiohttp                                  3.10.2
aiosignal                                1.3.1
alembic                                  1.13.2
annotated-types                          0.7.0
anthropic                                0.34.1
anyio                                    4.4.0
APScheduler                              3.10.4
argon2-cffi                              23.1.0
argon2-cffi-bindings                     21.2.0
asgiref                                  3.8.1
attrs                                    24.2.0
Authlib                                  1.3.1
av                                       12.3.0
backoff                                  2.2.1
bcrypt                                   4.2.0
beautifulsoup4                           4.12.3
bidict                                   0.23.1
bigdl-core-cpp                           2.5.0
black                                    24.8.0
blinker                                  1.8.2
boto3                                    1.35.0
botocore                                 1.35.4
build                                    1.2.1
cachetools                               5.5.0
certifi                                  2024.7.4
cffi                                     1.17.0
chardet                                  5.2.0
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.6
chromadb                                 0.5.5
click                                    8.1.7
colorama                                 0.4.6
colorclass                               2.2.2
coloredlogs                              15.0.1
compressed_rtf                           1.0.6
cryptography                             43.0.0
ctranslate2                              4.3.1
dataclasses-json                         0.6.7
deepdiff                                 7.0.1
defusedxml                               0.7.1
Deprecated                               1.2.14
distro                                   1.9.0
dnspython                                2.6.1
docker                                   7.1.0
docx2txt                                 0.8
dpcpp-cpp-rt                             2024.0.2
duckduckgo_search                        6.2.10
easygui                                  0.98.3
ebcdic                                   1.1.1
ecdsa                                    0.19.0
email_validator                          2.2.0
emoji                                    2.12.1
et-xmlfile                               1.1.0
extract-msg                              0.49.0
fake-useragent                           1.5.1
fastapi                                  0.111.0
fastapi-cli                              0.0.5
faster-whisper                           1.0.3
filelock                                 3.15.4
filetype                                 1.2.0
Flask                                    3.0.3
Flask-Cors                               4.0.1
flatbuffers                              24.3.25
fonttools                                4.53.1
fpdf2                                    2.7.9
frozenlist                               1.4.1
fsspec                                   2024.6.1
gguf                                     0.9.1
google-ai-generativelanguage             0.6.6
google-api-core                          2.19.1
google-api-python-client                 2.142.0
google-auth                              2.34.0
google-auth-httplib2                     0.2.0
google-generativeai                      0.7.2
googleapis-common-protos                 1.63.2
greenlet                                 3.0.3
grpcio                                   1.66.0
grpcio-status                            1.62.3
h11                                      0.14.0
httpcore                                 1.0.5
httplib2                                 0.22.0
httptools                                0.6.1
httpx                                    0.27.0
huggingface-hub                          0.24.6
humanfriendly                            10.0
idna                                     3.7
importlib_metadata                       8.0.0
importlib_resources                      6.4.4
iniconfig                                2.0.0
intel-cmplr-lib-rt                       2024.0.2
intel-cmplr-lic-rt                       2024.0.2
intel-opencl-rt                          2024.0.2
intel-openmp                             2024.0.2
ipex-llm                                 2.2.0b20240822
itsdangerous                             2.2.0
Jinja2                                   3.1.4
jiter                                    0.5.0
jmespath                                 1.0.1
joblib                                   1.4.2
jsonpatch                                1.33
jsonpath-python                          1.0.6
jsonpointer                              3.0.0
kubernetes                               30.1.0
langchain                                0.2.12
langchain-chroma                         0.1.2
langchain-community                      0.2.10
langchain-core                           0.2.34
langchain-text-splitters                 0.2.2
langdetect                               1.0.9
langfuse                                 2.43.3
langsmith                                0.1.104
lark                                     1.1.9
lxml                                     5.3.0
Mako                                     1.3.5
Markdown                                 3.6
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.22.0
mdurl                                    0.1.2
mkl                                      2024.0.0
mkl-dpcpp                                2024.0.0
mmh3                                     4.1.0
monotonic                                1.6
mpmath                                   1.3.0
msoffcrypto-tool                         5.4.2
multidict                                6.0.5
mypy-extensions                          1.0.0
nest-asyncio                             1.6.0
networkx                                 3.3
nltk                                     3.9.1
numpy                                    1.26.4
oauthlib                                 3.2.2
olefile                                  0.47
oletools                                 0.60.2
onednn                                   2024.0.0
onednn-devel                             2024.0.0
onemkl-sycl-blas                         2024.0.0
onemkl-sycl-datafitting                  2024.0.0
onemkl-sycl-dft                          2024.0.0
onemkl-sycl-lapack                       2024.0.0
onemkl-sycl-rng                          2024.0.0
onemkl-sycl-sparse                       2024.0.0
onemkl-sycl-stats                        2024.0.0
onemkl-sycl-vm                           2024.0.0
onnxruntime                              1.19.0
openai                                   1.42.0
opencv-python                            4.10.0.84
opencv-python-headless                   4.10.0.84
openpyxl                                 3.1.5
opentelemetry-api                        1.26.0
opentelemetry-exporter-otlp-proto-common 1.26.0
opentelemetry-exporter-otlp-proto-grpc   1.26.0
opentelemetry-instrumentation            0.47b0
opentelemetry-instrumentation-asgi       0.47b0
opentelemetry-instrumentation-fastapi    0.47b0
opentelemetry-proto                      1.26.0
opentelemetry-sdk                        1.26.0
opentelemetry-semantic-conventions       0.47b0
opentelemetry-util-http                  0.47b0
ordered-set                              4.1.0
orjson                                   3.10.7
overrides                                7.7.0
packaging                                23.2
pandas                                   2.2.2
passlib                                  1.7.4
pathspec                                 0.12.1
pcodedmp                                 1.2.6
peewee                                   3.17.6
peewee-migrate                           1.12.2
pillow                                   10.4.0
pip                                      24.2
platformdirs                             4.2.2
pluggy                                   1.5.0
posthog                                  3.5.2
primp                                    0.6.1
proto-plus                               1.24.0
protobuf                                 4.25.4
psutil                                   6.0.0
psycopg2-binary                          2.9.9
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pyclipper                                1.3.0.post5
pycparser                                2.22
pydantic                                 2.8.2
pydantic_core                            2.20.1
pydub                                    0.25.1
Pygments                                 2.18.0
PyJWT                                    2.9.0
pymongo                                  4.8.0
PyMySQL                                  1.1.1
pypandoc                                 1.13
pyparsing                                3.1.2
pypdf                                    4.3.1
PyPika                                   0.48.9
pyproject_hooks                          1.1.0
pyreadline3                              3.4.1
pytest                                   8.3.2
pytest-docker                            3.1.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-engineio                          4.9.1
python-iso639                            2024.4.27
python-jose                              3.3.0
python-magic                             0.4.27
python-multipart                         0.0.9
python-pptx                              1.0.0
python-socketio                          5.11.3
pytube                                   15.0.0
pytz                                     2024.1
pywin32                                  306
pyxlsb                                   1.0.10
PyYAML                                   6.0.2
rank-bm25                                0.2.2
rapidfuzz                                3.9.6
rapidocr-onnxruntime                     1.3.24
red-black-tree-mod                       1.20
redis                                    5.0.8
regex                                    2024.7.24
requests                                 2.32.3
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
rich                                     13.7.1
rsa                                      4.9
RTFDE                                    0.1.2
s3transfer                               0.10.2
safetensors                              0.4.4
scikit-learn                             1.5.1
scipy                                    1.14.1
sentence-transformers                    3.0.1
sentencepiece                            0.1.99
setuptools                               72.2.0
shapely                                  2.0.6
shellingham                              1.5.4
simple-websocket                         1.0.0
six                                      1.16.0
sniffio                                  1.3.1
soupsieve                                2.6
SQLAlchemy                               2.0.32
starlette                                0.37.2
sympy                                    1.13.2
tabulate                                 0.9.0
tbb                                      2021.13.1
tenacity                                 8.5.0
threadpoolctl                            3.5.0
tiktoken                                 0.7.0
tokenizers                               0.19.1
torch                                    2.2.0
tqdm                                     4.66.5
transformers                             4.44.2
typer                                    0.12.4
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.1
tzlocal                                  5.2
ujson                                    5.10.0
unstructured                             0.15.5
unstructured-client                      0.25.5
uritemplate                              4.1.1
urllib3                                  2.2.2
uvicorn                                  0.30.6
validators                               0.33.0
watchfiles                               0.23.0
websocket-client                         1.8.0
websockets                               13.0
Werkzeug                                 3.0.4
wheel                                    0.44.0
win_unicode_console                      0.5
wrapt                                    1.16.0
wsproto                                  1.2.0
xlrd                                     2.0.1
XlsxWriter                               3.2.0
yarl                                     1.9.4
youtube-transcript-api                   0.6.2
zipp                                     3.20.0

**Comment by brownplayer** [comment]
> 您好，您能否展示您为运行 open-webui 而安装的依赖项版本（pip list 显示的结果）？此外，你可以参考 [ipex-llm open-webui quickstart](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/open_webui_with_ollama_quickstart.md) 来准备你的环境。

Yes, I followed the official guidelines

**Comment by brownplayer** [comment]
> 您好，您能否展示您为运行 open-webui 而安装的依赖项版本（pip list 显示的结果）？此外，你可以参考 [ipex-llm open-webui quickstart](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/open_webui_with_ollama_quickstart.md) 来准备你的环境。

of course
Package                                  Version
---------------------------------------- --------------
accelerate                               0.21.0
aiohappyeyeballs                         2.4.0
aiohttp                                  3.10.2
aiosignal                                1.3.1
alembic                                  1.13.2
annotated-types                          0.7.0
anthropic                                0.34.1
anyio                                    4.4.0
APScheduler                              3.10.4
argon2-cffi                              23.1.0
argon2-cffi-bindings                     21.2.0
asgiref                                  3.8.1
attrs                                    24.2.0
Authlib                                  1.3.1
av                                       12.3.0
backoff                                  2.2.1
bcrypt                                   4.2.0
beautifulsoup4                           4.12.3
bidict                                   0.23.1
bigdl-core-cpp                           2.5.0
black                                    24.8.0
blinker                                  1.8.2
boto3                                    1.35.0
botocore                                 1.35.4
build                                    1.2.1
cachetools                               5.5.0
certifi                                  2024.7.4
cffi                                     1.17.0
chardet                                  5.2.0
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.6
chromadb                                 0.5.5
click                                    8.1.7
colorama                                 0.4.6
colorclass                               2.2.2
coloredlogs                              15.0.1
compressed_rtf                           1.0.6
cryptography                             43.0.0
ctranslate2                              4.3.1
dataclasses-json                         0.6.7
deepdiff                                 7.0.1
defusedxml                               0.7.1
Deprecated                               1.2.14
distro                                   1.9.0
dnspython                                2.6.1
docker                                   7.1.0
docx2txt                                 0.8
dpcpp-cpp-rt                             2024.0.2
duckduckgo_search                        6.2.10
easygui                                  0.98.3
ebcdic                                   1.1.1
ecdsa                                    0.19.0
email_validator                          2.2.0
emoji                                    2.12.1
et-xmlfile                               1.1.0
extract-msg                              0.49.0
fake-useragent                           1.5.1
fastapi                                  0.111.0
fastapi-cli                              0.0.5
faster-whisper                           1.0.3
filelock                                 3.15.4
filetype                                 1.2.0
Flask                                    3.0.3
Flask-Cors                               4.0.1
flatbuffers                              24.3.25
fonttools                                4.53.1
fpdf2                                    2.7.9
frozenlist                               1.4.1
fsspec                                   2024.6.1
gguf                                     0.9.1
google-ai-generativelanguage             0.6.6
google-api-core                          2.19.1
google-api-python-client                 2.142.0
google-auth                              2.34.0
google-auth-httplib2                     0.2.0
google-generativeai                      0.7.2
googleapis-common-protos                 1.63.2
greenlet                                 3.0.3
grpcio                                   1.66.0
grpcio-status                            1.62.3
h11                                      0.14.0
httpcore                                 1.0.5
httplib2                                 0.22.0
httptools                                0.6.1
httpx                                    0.27.0
huggingface-hub                          0.24.6
humanfriendly                            10.0
idna                                     3.7
importlib_metadata                       8.0.0
importlib_resources                      6.4.4
iniconfig                                2.0.0
intel-cmplr-lib-rt                       2024.0.2
intel-cmplr-lic-rt                       2024.0.2
intel-opencl-rt                          2024.0.2
intel-openmp                             2024.0.2
ipex-llm                                 2.2.0b20240822
itsdangerous                             2.2.0
Jinja2                                   3.1.4
jiter                                    0.5.0
jmespath                                 1.0.1
joblib                                   1.4.2
jsonpatch                                1.33
jsonpath-python                          1.0.6
jsonpointer                              3.0.0
kubernetes                               30.1.0
langchain                                0.2.12
langchain-chroma                         0.1.2
langchain-community                      0.2.10
langchain-core                           0.2.34
langchain-text-splitters                 0.2.2
langdetect                               1.0.9
langfuse                                 2.43.3
langsmith                                0.1.104
lark                                     1.1.9
lxml                                     5.3.0
Mako                                     1.3.5
Markdown                                 3.6
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.22.0
mdurl                                    0.1.2
mkl                                      2024.0.0
mkl-dpcpp                                2024.0.0
mmh3                                     4.1.0
monotonic                                1.6
mpmath                                   1.3.0
msoffcrypto-tool                         5.4.2
multidict                                6.0.5
mypy-extensions                          1.0.0
nest-asyncio                             1.6.0
networkx                                 3.3
nltk                                     3.9.1
numpy                                    1.26.4
oauthlib                                 3.2.2
olefile                                  0.47
oletools                                 0.60.2
onednn                                   2024.0.0
onednn-devel                             2024.0.0
onemkl-sycl-blas                         2024.0.0
onemkl-sycl-datafitting                  2024.0.0
onemkl-sycl-dft                          2024.0.0
onemkl-sycl-lapack                       2024.0.0
onemkl-sycl-rng                          2024.0.0
onemkl-sycl-sparse                       2024.0.0
onemkl-sycl-stats                        2024.0.0
onemkl-sycl-vm                           2024.0.0
onnxruntime                              1.19.0
openai                                   1.42.0
opencv-python                            4.10.0.84
opencv-python-headless                   4.10.0.84
openpyxl                                 3.1.5
opentelemetry-api                        1.26.0
opentelemetry-exporter-otlp-proto-common 1.26.0
opentelemetry-exporter-otlp-proto-grpc   1.26.0
opentelemetry-instrumentation            0.47b0
opentelemetry-instrumentation-asgi       0.47b0
opentelemetry-instrumentation-fastapi    0.47b0
opentelemetry-proto                      1.26.0
opentelemetry-sdk                        1.26.0
opentelemetry-semantic-conventions       0.47b0
opentelemetry-util-http                  0.47b0
ordered-set                              4.1.0
orjson                                   3.10.7
overrides                                7.7.0
packaging                                23.2
pandas                                   2.2.2
passlib                                  1.7.4
pathspec                                 0.12.1
pcodedmp                                 1.2.6
peewee                                   3.17.6
peewee-migrate                           1.12.2
pillow                                   10.4.0
pip                                      24.2
platformdirs                             4.2.2
pluggy                                   1.5.0
posthog                                  3.5.2
primp                                    0.6.1
proto-plus                               1.24.0
protobuf                                 4.25.4
psutil                                   6.0.0
psycopg2-binary                          2.9.9
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pyclipper                                1.3.0.post5
pycparser                                2.22
pydantic                                 2.8.2
pydantic_core                            2.20.1
pydub                                    0.25.1
Pygments                                 2.18.0
PyJWT                                    2.9.0
pymongo                                  4.8.0
PyMySQL                                  1.1.1
pypandoc                                 1.13
pyparsing                                3.1.2
pypdf                                    4.3.1
PyPika                                   0.48.9
pyproject_hooks                          1.1.0
pyreadline3                              3.4.1
pytest                                   8.3.2
pytest-docker                            3.1.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-engineio                          4.9.1
python-iso639                            2024.4.27
python-jose                              3.3.0
python-magic                             0.4.27
python-multipart                         0.0.9
python-pptx                              1.0.0
python-socketio                          5.11.3
pytube                                   15.0.0
pytz                                     2024.1
pywin32                                  306
pyxlsb                                   1.0.10
PyYAML                                   6.0.2
rank-bm25                                0.2.2
rapidfuzz                                3.9.6
rapidocr-onnxruntime                     1.3.24
red-black-tree-mod                       1.20
redis                                    5.0.8
regex                                    2024.7.24
requests                                 2.32.3
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
rich                                     13.7.1
rsa                                      4.9
RTFDE                                    0.1.2
s3transfer                               0.10.2
safetensors                              0.4.4
scikit-learn                             1.5.1
scipy                                    1.14.1
sentence-transformers                    3.0.1
sentencepiece                            0.1.99
setuptools                               72.2.0
shapely                                  2.0.6
shellingham                              1.5.4
simple-websocket                         1.0.0
six                                      1.16.0
sniffio                                  1.3.1
soupsieve                                2.6
SQLAlchemy                               2.0.32
starlette                                0.37.2
sympy                                    1.13.2
tabulate                                 0.9.0
tbb                                      2021.13.1
tenacity                                 8.5.0
threadpoolctl                            3.5.0
tiktoken                                 0.7.0
tokenizers                               0.19.1
torch                                    2.2.0
tqdm                                     4.66.5
transformers                             4.44.2
typer                                    0.12.4
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.1
tzlocal                                  5.2
ujson                                    5.10.0
unstructured                             0.15.5
unstructured-client                      0.25.5
uritemplate                              4.1.1
urllib3                                  2.2.2
uvicorn                                  0.30.6
validators                               0.33.0
watchfiles                               0.23.0
websocket-client                         1.8.0
websockets                               13.0
Werkzeug                                 3.0.4
wheel                                    0.44.0
win_unicode_console                      0.5
wrapt                                    1.16.0
wsproto                                  1.2.0
xlrd                                     2.0.1
XlsxWriter                               3.2.0
yarl                                     1.9.4
youtube-transcript-api                   0.6.2
zipp                                     3.20.0

**Comment by sgwhat** [comment]
Same as https://github.com/intel-analytics/ipex-llm/issues/11907
