### ISSUE TITLE
Cannot run llama3.1 models with ollama

### ISSUE THREAD

**Issue by tkarna** [intel-analytics/ipex-llm#11911]
I've installed ipex-llm with llama.cpp and ollama support following the instructions:
```bash
pip install --pre --upgrade ipex-llm[cpp]
init-llama-cpp
init-ollama
```

I'm trying to use model `llama3.1:8b-instruct-q4_K_M` with ollama and langchain. When downloading the model with ollama I get an error:

```txt
$ ollama pull llama3.1:8b-instruct-q4_K_M

Error: pull model manifest: 412: 

The model you are attempting to pull requires a newer version of Ollama.

Please download the latest version at:

        https://ollama.com/download
```

ipex-llm version is 2.2.0b20240822

Minimal reproducer:

```python
from langchain_community.llms import Ollama

llm = Ollama(model="llama3.1:8b-instruct-q4_K_M")

q = "What is the capital of Spain?"
print(f"Query: {q}")
response = llm.invoke(q)
print('Response:')
print(response)
```

Execution:
```bash
pip install langchain langchain_community
./ollama serve &
python test.py
```

**Comment by rnwang04** [comment]
Hi @tkarna ,
> ```
> $ ollama pull llama3.1:8b-instruct-q4_K_M
> 
> Error: pull model manifest: 412: 
> 
> The model you are attempting to pull requires a newer version of Ollama.
> 
> Please download the latest version at:
> 
>         https://ollama.com/download
 
Maybe try it again with ` $ ./ollama serve` / ` $ ./ollama pull llama3.1:8b-instruct-q4_K_M` under your ollama directory ?
The error looks like you are not using ipex-llm's ollama, instead of an old community ollama.

**Comment by tkarna** [comment]
Thanks, an older version of ollama was indeed interfering. Fixed that now. I can pull the model correctly. But when I run the example, I get an error:

```txt
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291
```

Can you reproduce this?
Possibly related: https://github.com/abetlen/llama-cpp-python/issues/1646

**Comment by rnwang04** [comment]
Here is a related user issue: https://github.com/intel-analytics/ipex-llm/issues/11836
But I think we have fixed it. Could you please check it again ?

**Comment by rnwang04** [comment]
Glad to hear to that : )
