### ISSUE TITLE
An error occurred while running mistral-nemo in ollama

### ISSUE THREAD

**Issue by brownplayer** [intel-analytics/ipex-llm#11917]
There is an error when running mistral nemo in ollama, but there is no problem when running qwen0.5b/It seems that ollama version is too low, how can I upgrade ollama version
![屏幕截图 2024-08-25 142723](https://github.com/user-attachments/assets/437eebab-6e04-4a7a-bc7b-cf74a1fa1431)

**Comment by sgwhat** [comment]
Hi @brownplayer , the current version of `ipex-llm ollama` can be found in the [Ollama QuickStart](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md). We do not support users upgrading it themselves, but we will be updating the ollama version in recent days.

**Comment by brownplayer** [comment]
That's great, thanks for your contributions, I can't wait to try the latest ollama

---- Replied Message ----
| From | SONG ***@***.***> |
| Date | 08/26/2024 10:21 |
| To | intel-analytics/ipex-llm ***@***.***> |
| Cc | brownplayer ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [intel-analytics/ipex-llm] An error occurred while running mistral-nemo in ollama (Issue #11917) |

Hi @brownplayer , the current version of ipex-llm ollama can be found in the Ollama QuickStart. We do not support users upgrading it themselves, but we will be updating the ollama version in recent days.

**Comment by rnwang04** [comment]
Hi @brownplayer ,
ipex-llm‘s ollama is upgrade to 0.3.6 with `ipex-llm[cpp]>=2.2.0b20240827`, you may have a try with latest llama.cpp / ollama 😊

**Comment by brownplayer** [comment]
wow，it's so great
