### ISSUE TITLE
Error 403 occurs when the browser plug-in calls the ollama api

### ISSUE THREAD

**Issue by brownplayer** [intel-analytics/ipex-llm#11916]
Error 403 occurs when the browser plug-in calls the ollama api
![image](https://github.com/user-attachments/assets/0a346489-0a68-4b7f-8598-e6f0c3c56dd5)
The cors unblock plug-in is enabled on the browser

**Comment by sgwhat** [comment]
Hi @brownplayer , I am not able to reproduce your issue, could you please provide the detailed cmd that you ran ollama api? By the way, you may set your env before running `ollama serve` as below:
```
set OLLAMA_NUM_GPU=999
set no_proxy=localhost,127.0.0.1
set ZES_ENABLE_SYSMAN=1
set SYCL_CACHE_PERSISTENT=1
set SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1

ollama serve
```

**Comment by brownplayer** [comment]
Thanks for your reply, I have solved the problem by adding set OLLAMA_ORIGINS=chrome-extension://* to the environment variable
