### ISSUE TITLE
support inference AWQ INT4 model of Yi-34B from QLoRA

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#11946]
I will provide AWQ model from customer, and customer will evaluate FP8 and Int4 performance.

**Comment by gc-fu** [comment]
Hi, I have verified AWQ models can be supported (loaded in vLLM and converted to LowBitLinear in ipex-llm), but only asym_int4 quantization format is supported.

This feature will need some adaption from both vLLM side and ipex-llm side.  I will update to this thread once those supported prs are merged.

**Comment by glorysdj** [comment]
fixed
