### ISSUE TITLE
Running  vLLM service benchmark(4xARC770) with Qwen1.5-32B-Chat model failed

### ISSUE THREAD

**Issue by dukelee111** [intel-analytics/ipex-llm#11956]
Environment:
Platform:   6548N+4ARC770
Docker Image: intelanalytics/ipex-llm-serving-xpu:2.1.0
servicing script:
![image](https://github.com/user-attachments/assets/3949f088-d83f-4844-9ab3-0f0c98604792)

Error info:
1.With Dtype SYM_INT4 could succeed.
2.With Dtype FP8 failed with concurrency>=4. No error for concurrency 1 and 2.
2.GPU card 0 shows N/A utilization, card 1 2 3 work well:
![image](https://github.com/user-attachments/assets/92cff217-632e-4ff4-8601-2917ddbd9d30)
3.Servicing side error log:
![image](https://github.com/user-attachments/assets/ce64825a-21d4-4039-aa57-0355e69d382c)
4.Client error info:
![image](https://github.com/user-attachments/assets/b4159aa8-1add-44bb-a5c3-65a50afa7d7f)

**Comment by hzjane** [comment]
It seems that the gpu-memory-utilization is too high and causing the card 1 OOM when first_token is computed. You can reduce it to 0.85 can try ir again.

**Comment by glorysdj** [comment]
fixed
