### ISSUE TITLE
Qwen2 in benchmark all-in-one fails (NotImplementedError: Cannot copy out of meta tensor; no data!)

### ISSUE THREAD

**Issue by yeonbok** [intel-analytics/ipex-llm#12000]
Hello, 
I tried to run Qwen2 with the following config.
 
(changed configs;)
repo_id : Qwen/Qwen2-7B
in_out_pairs: - '1024-128'
test_api: - "transformer_int4_fp16_gpu_win"

However, it failed as below: 

 python .\run.py
C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-09-04 07:26:23,245 - INFO - intel_extension_for_pytorch auto imported
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:20<00:00,  3.43s/it]
Traceback (most recent call last):
  File "C:\dev\taylor\ipex-llm\python\llm\dev\benchmark\all-in-one\run.py", line 2066, in <module>
    run_model(model, api, in_out_pairs, conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'],
  File "C:\dev\taylor\ipex-llm\python\llm\dev\benchmark\all-in-one\run.py", line 170, in run_model
    result = run_transformer_int4_fp16_gpu_win(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams, low_bit, cpu_embedding, batch_size, streaming)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\taylor\ipex-llm\python\llm\dev\benchmark\all-in-one\run.py", line 1149, in run_transformer_int4_fp16_gpu_win
    model = AutoModelForCausalLM.from_pretrained(model_path, optimize_model=True, load_in_low_bit=low_bit,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\unittest\mock.py", line 1378, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\ipex_llm\transformers\model.py", line 366, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\ipex_llm\transformers\model.py", line 520, in load_convert
    model = model.to("cpu")
            ^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\transformers\modeling_utils.py", line 2597, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\MTL\miniforge3\envs\taylor_ipex\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**NotImplementedError: Cannot copy out of meta tensor; no data!**

Could I get help with resolving this issue? 
Thanks!

**Comment by Oscilloscope98** [comment]
Hi @yeonbok,

We did not reproduced your issue. Would you mind providing us with more information regarding your test environment through pasting the log of [our env-check script](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts#env-check)?

**Comment by yeonbok** [comment]
@Oscilloscope98 Hi, i could run with same setup for llama3 and chatglm3. Only Qwen was failing with that error. Below is the env check log.
@echo off

REM Check Python version
python -V
if ERRORLEVEL 1 ( 
    echo No Python found! Instructions on how to create an environment can be found in the README.md.
    goto:end
)
python check.py

echo -----------------------------------------------------------------
echo System Information
systeminfo
echo -----------------------------------------------------------------
xpu-smi discovery
if ERRORLEVEL 1 ( 
    echo xpu-smi is not installed properly. 
    goto:end
)

:end

**Comment by Oscilloscope98** [comment]
Hi @yeonbok,

It seems that the `Qwen\Qwen2-7B` model you are using is not the same as the latest one on Hugging Face (you have 6 checkpoints to load, and there are only 4 checkpoints on Hugging Face now): https://huggingface.co/Qwen/Qwen2-7B/tree/main

Would you mind having a try on the latest Qwen2-7B model or share us with the model you are using? :)

**Comment by yeonbok** [comment]
Thank you very much @Oscilloscope98! It is working with the new model.
