### ISSUE TITLE
Ollama Error on MTL-iGPU 

### ISSUE THREAD

**Issue by weiseng-yeap** [intel-analytics/ipex-llm#12037]
Hi IPEX-LLM Team.

We testing the OLLAMA follow this guide:
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md

The platform that we using is MTL iGPU and ubuntu 22.04

And tested on oneAPI version 2024.1 & 2024.2 detected same issue.

Steps:
1. On terminal input command ./ollama serve
2. On 2nd terminal input command ./ollma run phi3

Error:
![image](https://github.com/user-attachments/assets/479255c5-d813-433c-9f9b-1952c681e30b)

**Comment by sgwhat** [comment]
Hi @weiseng-yeap, you may try to install oneAPI 2024.0 and run phi3 again, it works fine based on my testing.
