### ISSUE TITLE
vllm not support CodeShell model

### ISSUE THREAD

**Issue by YongZhuIntel** [intel-analytics/ipex-llm#12078]
I got an error when trying to run CodeShell-7B-Chat model with vllm：
```
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/model_executor/model
_loader/loader.py", line 151, in _initialize_model
    model_class = get_model_architecture(model_config)[0]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/model_executor/model
_loader/utils.py", line 35, in get_model_architecture
    raise ValueError(
ValueError: Model architectures ['CodeShellForCausalLM'] are not supported for now. Supported architectures: ['A
quilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'Blip2ForCon
ditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'Co
hereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'Falco
nForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCaus
alLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'InternVLChatMode
l', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration',
 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'M
PTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPMV', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'O
rionForCausalLM', 'PersimmonForCausalLM', 'PaliGemmaForConditionalGeneration', 'PhiForCausalLM', 'Phi3ForCausalL
M', 'Phi3VForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLM
EpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Ph
i3SmallForCausalLM', 'MedusaModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'MistralModel']
```
The script is as following:
```
model="/llm/models/WisdomShell/CodeShell-7B-Chat"
served_model_name="CodeShell-7B-Chat"
export USE_XETLA=OFF
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
export SYCL_CACHE_PERSISTENT=1
export TORCH_LLM_ALLREDUCE=0
export CCL_DG2_ALLREDUCE=1
# Tensor parallel related arguments:
export CCL_WORKER_COUNT=2
export FI_PROVIDER=shm
export CCL_ATL_TRANSPORT=ofi
export CCL_ZE_IPC_EXCHANGE=sockets
export CCL_ATL_SHM=1
source /opt/intel/oneapi/setvars.sh --force
source /opt/intel/1ccl-wks/setvars.sh
python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server \
--served-model-name $served_model_name \
--port 8000 \
--model $model \
--trust-remote-code \
--gpu-memory-utilization 0.95 \
--device xpu \
--dtype float16 \
--enforce-eager \
--load-in-low-bit fp8 \
--max-model-len 2048 \
--max-num-batched-tokens 4000 \
--tensor-parallel-size 2
```

**Comment by hzjane** [comment]
I follow [this repo](https://github.com/WisdomShell/vllm_for_codeshell/commits/v0.5.3/) to test running `CodeShell-7B-Chat` but encounter this error `RuntimeError: Unsupported block size: 64`. I now try to solve it to run.

**Comment by hzjane** [comment]
Refer to this [repo](https://github.com/WisdomShell/vllm_for_codeshell/tree/v0.5.3).
On image intelanalytics/ipex-llm-serving-xpu-vllm-0.5.4-experimental:2.2.0b1, you can hard code run it.

Add these two files  https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/model_executor/models/codeshell.py and https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/transformers_utils/configs/codeshell.py.
Update https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/model_executor/models/__init__.py#L77 like
```
    "JambaForCausalLM": ("jamba", "JambaForCausalLM"),
    "CodeShellForCausalLM": ("codeshell", "CodeShellForCausalLM")
```
and update https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/config.py#L364 like
```bash
            # For ChatGLM:
            "multi_query_group_num",
            # For CodeShell
            "num_query_groups"

**Comment by glorysdj** [comment]
> Refer to this [repo](https://github.com/WisdomShell/vllm_for_codeshell/tree/v0.5.3). On image intelanalytics/ipex-llm-serving-xpu-vllm-0.5.4-experimental:2.2.0b1, you can hard code run it.
> 
> Add these two files https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/model_executor/models/codeshell.py and https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/transformers_utils/configs/codeshell.py. Update https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/model_executor/models/__init__.py#L77 like
> 
> ```
>     "JambaForCausalLM": ("jamba", "JambaForCausalLM"),
>     "CodeShellForCausalLM": ("codeshell", "CodeShellForCausalLM")
> ```
> 
> and update https://github.com/WisdomShell/vllm_for_codeshell/blob/v0.5.3/vllm/config.py#L364 like
> 
> ```shell
>             # For ChatGLM:
>             "multi_query_group_num",
>             # For CodeShell
>             "num_query_groups"
> ```
