### ISSUE TITLE
 Unsupported SPIR-V version

### ISSUE THREAD

**Issue by Pablou2902** [intel-analytics/ipex-llm#12168]
I was following this guide: https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md and everything worked as intented until I tried to follow the last example. When I try to compile it, I get the following error:
![image](https://github.com/user-attachments/assets/70abc657-22bd-4946-a00d-849d39665c51)
Also tried with this guide https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md and happened exactly the same. Im new on this, so if there's a solution I ask to be very specific on how to implement it.

**Comment by Oscilloscope98** [comment]
Hi @Pablou2902,

Would you mind running our [env check scripts](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts#env-check) and pasting the output here, as well as providing us with your GPU device name & GPU driver version, to give us more information so that we could better reproduce your problem? :)

**Comment by Pablou2902** [comment]
Hi,
Here you have the output you requested: 
[output.txt](https://github.com/user-attachments/files/17356945/output.txt)
About the GPU, I'm currently testing Integrated Graphics performance while trying to run LLM's.
-Device Name: Intel(R) Iris(R) Xe Graphics
-Driver version: 30.0.101.3111

**Comment by Oscilloscope98** [comment]
Hi @Pablou2902,.

It seems like your GPU driver version is too old. You could [update your GPU driver](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) to the latest one and have a try again :)

Please let us know for any further problems.

**Comment by Pablou2902** [comment]
Yeah, this definetely worked. Thank you so much for your help!
