### ISSUE TITLE
[NPU] Typo in npu_model.py causes error when perform load_low_bit function

### ISSUE THREAD

**Issue by climh** [intel-analytics/ipex-llm#12343]
Syntax error in https://github.com/intel-analytics/ipex-llm/blob/899a30331abbfae62cdf126b9d62e8d0469c715f/python/llm/src/ipex_llm/transformers/npu_model.py#L552C32-L552C47

where **_max_output_len_** suppose to be **_max_context_len_**

**Comment by plusbang** [comment]
Hi, @climh , thank you for pointing out this bug! We will fix it soon : )
