### ISSUE TITLE
Docker - llama.cpp scripts / init-llama-cpp

### ISSUE THREAD

**Issue by easyfab** [intel-analytics/ipex-llm#12379]
Are docker/llm/inference-cpp/start-llama-cpp.sh and docker/llm/inference-cpp/benchmark_llama-cpp.sh up to date ?

I see this scripts using ./main, the current version of ipex llama.cpp are llama-cli and llama-bench if i'm not mistaken.

Could init-llama-cpp be launch when starting the file docker container to enable the usage of entrypoint ?

**Comment by glorysdj** [comment]
fixed by https://github.com/intel-analytics/ipex-llm/pull/12387

**Comment by easyfab** [comment]
Thank you
