### ISSUE TITLE
Container cannot see Arc GPU

### ISSUE THREAD

**Issue by robertvazan** [intel-analytics/ipex-llm#12372]
I am following the [IPEX Ollama docker guide](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/DockerGuides/docker_cpp_xpu_quickstart.md). I am stuck on the `sycl-ls` step. The container cannot see Arc GPU even though the host can and the container has `/dev/dri` shared and it even runs `--privileged`.

Here's what I see in the container:

```
# ls /dev/dri
card1  card2  renderD128  renderD129
# whoami
root
# sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2023.16.12.0.12_195853.xmain-hotfix]
[opencl:cpu:1] Intel(R) OpenCL, AMD Ryzen 5 5600G with Radeon Graphics          OpenCL 3.0 (Build 0) [2023.16.12.0.12_195853.xmain-hotfix]
```

Meantime, it seems to work on the host:

```
$ ls /dev/dri
by-path  card1  card2  renderD128  renderD129
$ whoami
rv
$ source /opt/intel/oneapi/setvars.sh
$ sycl-ls
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Arc(TM) A380 Graphics 12.56.5 [1.3.30049.600000]
[opencl:cpu][opencl:0] Intel(R) OpenCL, AMD Ryzen 5 5600G with Radeon Graphics          OpenCL 3.0 (Build 0) [2024.18.10.0.08_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A380 Graphics OpenCL 3.0 NEO  [24.26.30049.6]
```

This is how I start the container:

```
sudo podman run -it --rm \
    --privileged \
    --device=/dev/dri \
    -v ollama-ipex:/models \
    --name ollama-ipex \
    docker.io/intelanalytics/ipex-llm-inference-cpp-xpu:latest
```

The [guide](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/DockerGuides/docker_cpp_xpu_quickstart.md) prescribes all sorts of additional parameters for the container, but adding them makes no difference.

Per info on [Docker Hub page](https://hub.docker.com/r/intelanalytics/ipex-llm-inference-cpp-xpu/tags), this image is still updated daily, but I am starting to think there is something wrong with it. Library versions reported by `sycl-ls` in the container are from 2023.

**Comment by pepijndevos** [comment]
Same here, I just tried the guide and my Arc A770 is not visible.

Meanwhile, this image works fine for me: https://github.com/mattcurf/ollama-intel-gpu

**Comment by liu-shaojun** [comment]
Hi @robertvazan @pepijndevos 
Could you provide the kernel version and gpu driver version?
```
uname -r
dpkg -l | grep i915
modinfo i915
```

**Comment by liu-shaojun** [comment]
Hi @pepijndevos 

We recommend setting up your environment with **Kernel 6.5**, and installing the **Intel-i915-dkms** driver for optimal performance. We've tested Kernel 6.5 with the Intel-i915-dkms driver, and it successfully detects the GPU within the container. You can follow the steps below to install Kernel 6.5:

```bash
export VERSION="6.5.0-35"
sudo apt-get install -y linux-headers-$VERSION-generic
sudo apt-get install -y linux-image-$VERSION-generic
sudo apt-get install -y linux-modules-$VERSION-generic # may not be needed
sudo apt-get install -y linux-modules-extra-$VERSION-generic
```

After installing, you can configure GRUB to use the new kernel by running the following:

```bash
sudo sed -i "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=\"1> $(echo $(($(awk -F\' '/menuentry / {print $2}' /boot/grub/grub.cfg \
| grep -no $VERSION | sed 's/:/\n/g' | head -n 1)-2)))\"/" /etc/default/grub
```

Then, update GRUB and reboot your system:

```bash
sudo update-grub
sudo reboot
```

For detailed instructions on installing the driver, you can follow this link:  
[https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_linux_gpu.md#for-linux-kernel-65](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_linux_gpu.md#for-linux-kernel-65)

Please feel free to reach out if you have any questions!

**Comment by pepijndevos** [comment]
I'm on Arch Linux so that doesn't help much. I'd also like to point out again that the third party docker image linked above does detect my GPU. Maybe that image has newer userspace drivers than yours? I'll just keep using that one for now.

**Comment by robertvazan** [comment]
@liu-shaojun I am on Fedora and kernel 6.11.6. The [third-party image](https://github.com/mattcurf/ollama-intel-gpu) recommended by @pepijndevos works for me, likely thanks to newer versions of Intel libraries. Why wouldn't you upgrade your reference image? Would that break it on the oldest supported Ubuntu hosts?

While I am more than happy to give your software its favorite OS inside the container and to run sufficiently recent host kernel, limiting host kernel to a 2-3 specific versions is unreasonably restrictive for consumer hardware. It means worse support for your consumer GPUs than what AMD offers.

**Comment by liu-shaojun** [comment]
Hi @pepijndevos @robertvazan 

Our Docker image is based on this base image: `intel/oneapi-basekit:2024.1.1-devel-ubuntu22.04`. We have observed that in certain scenarios with specific kernel versions, such as kernel 6.8 without out-of-tree driver installed, GPUs are not detected inside containers started with `intel/oneapi-basekit:2024.1.1-devel-ubuntu22.04`. We are currently working on resolving this issue.

**Comment by liu-shaojun** [comment]
Hi @pepijndevos @robertvazan 

Could you please try using the `intelanalytics/ipex-llm-inference-cpp-xpu:latest` image? We've updated the compute runtime version in this image and tested it with kernel 6.8, where the GPU is detectable within the container.

**Comment by robertvazan** [comment]
@liu-shaojun The updated image works for me. Arc GPU is detected. No need for `--privileged` and other options mentioned in the quickstart guide. Are you going to update the guide too?

**Comment by liu-shaojun** [comment]
Sure, we will update the guide. Thanks for let us know!

**Comment by pepijndevos** [comment]
It sees my GPU!
