### ISSUE TITLE
Path of models using Ollama with IPEX-LLM (Windows)

### ISSUE THREAD

**Issue by NikosDi** [intel-analytics/ipex-llm#12403]
Hello.
I'm trying to figure out the path of the downloaded models when I run:

`ollama pull <model name> `

using the version of Ollama with IPEX-LLM.

It's not `C:\Users\<username>\.ollama\models` (obviously)

**Comment by sgwhat** [comment]
Actually it should be `C:\Users\<username>\.ollama\models` as default.

**Comment by NikosDi** [comment]
Well, no.

I tried to search the model after downloading it and it should be easy due to the size (> 4GB) but it was invisible - search couldn't find it.
So, I had to monitor the download procedure in real-time and I discovered that the path actually is:

`C:\Windows\System32\config\systemprofile\.ollama\models`

How can I set the default path to another location ? (e.g `C:\Users\<username>\.ollama\models`)

**Comment by NikosDi** [comment]
It works like a charm.

I had already seen the suggestion in FAQ and suggestions of "community ollama" but somehow I think this "Intel's ollama IPEX-LLM" version is something different with its own settings.
