### ISSUE TITLE
Error loading for file torch\lib\backend_with_compiler.dll

### ISSUE THREAD

**Issue by LiangtaoJin** [intel-analytics/ipex-llm#12428]
After installed IPEX-LLM with MTL AOT+PyTorch 2.3, there is Error loading for file torch\lib\backend_with_compiler.dll.

1. create python 3.11 conda environment with ipex-llm:

install ipex & ipex-llm with command:pip install -pre --upgrade ipex-llm[xpu_lnl]==2.2.0b2  -extra-index-url https://pytorch-extension.intel.com/release-whl/stable/mtl/cn/
pip uninstall torch torchvision intel_extension_for_pytorch -y

pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/mtl/cn/

2. start jupyter and execute command in cell:(eval.py will import torch)
!python eval.py --model_path ./models/qwen-lora --eval_type validation

3. Reported following error:
The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\Local_Admin\AppData\Local\Programs\IntelAIDevZone\notebooks\aigc_apps\eval.py", line 18, in <module>
    import torch
  File "C:\Users\Local_Admin\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch_init_.py", line 132, in <module>
    raise err
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Local_Admin\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

4. If import torch in cell directly there is no error.

**Comment by LiangtaoJin** [comment]
Will close the issue. The root cause is double imported pandas.
import pandas as pd
import torch
import json
import csv
import pathlib
import pandas as pd

**Comment by rkilchmn** [comment]
encountering same issue but not sure where the double imported pandas need to be fixed?
