### ISSUE TITLE
init-ollama.bat Not Working

### ISSUE THREAD

**Issue by imabdul-dev** [intel-analytics/ipex-llm#12465]
I unable to run ipex with llama.cpp, it is not working for ollama.

Device: Lenovo ThinkPad
OS: Windows 11
GPU: Iris Xe
GPU Driver: 32.0.101.6299

I followed the step by step

```
conda create -n llm-cpp python=3.11
conda activate llm-cpp
pip install --pre --upgrade ipex-llm[cpp]
```

```
mkdir ipex-ollama
cd ipex-ollama
```

But when I try `init-ollama.bat` it is saying that 'init-ollama.bat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sgwhat** [comment]
Hi @imabdul-dev, please run `init-ollama.bat` with administrator privilege in Miniforge Prompt.

**Comment by imabdul-dev** [comment]
As you can see in the screenshot I am Miniforge prompt is in admin mode but still getting error.
![image](https://github.com/user-attachments/assets/a6109714-1824-49d4-ad68-6e894f2ff1b7)

**Comment by imabdul-dev** [comment]
first I have to create a conda environment and activate it and then install ipex-llm[cpp] and then.  And after activating the previously created conda environment as admin and then initialize the ollama with `.init-ollama.bat` I already have installed the intel oneapi base. Am I right?

**Comment by imabdul-dev** [comment]
@sgwhat  It is working now. Actually, at first I use python 3.13 instead of 3.11, and after figuring out that it is not working then I use python 3.11, but it uses the cached pip packages, and that's why some packages were missing.
But now after clearing all the cache I've successfully installed the ollama with ipex-llm[cpp] but now the issue is that it is not detecting intel GPU.

**Comment by imabdul-dev** [comment]
It is working now. Thanks!
