### ISSUE TITLE
Cannot find dGPU when install ollama on Windows

### ISSUE THREAD

**Issue by yshuai** [intel-analytics/ipex-llm#12547]
I had install the oneapi, update latest  intel driver . 
After I installed ollama according to the tutorial  [Run Ollama with IPEX-LLM on Intel GPU](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md) 

![Run Ollama with IPEX-LLM on Intel GPU](https://github.com/user-attachments/assets/9f506ea5-2503-4e0f-bf73-cc078b9a4f33)

and when I exec  "ollama serve",I get the image
![image](https://github.com/user-attachments/assets/9f25451e-cd02-44f6-8fc6-a9b810c72505)

![image](https://github.com/user-attachments/assets/f3bc126c-d551-48da-bea0-8e913fff7198)

I have set the system environment variable
![image](https://github.com/user-attachments/assets/1e47e477-4813-4a7f-b56f-091db53f379c)

**Comment by MarsSovereign** [comment]
same problem, the new ollama client terminal in ipex-llm[cpp] may have some issues

**Comment by sgwhat** [comment]
Hi @yshuai @MarsSovereign, 

On the Ollama server side, it is observed that the CPU usage log is normal, we will update this log soon. After running `ollama run <model>`, it will run on the GPU. Please also refer to the Troubleshooting section in [ipex-llm ollama documentation](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md#5-using-ollama).

**Comment by yshuai** [comment]
@sgwhat Thank you,According to your suggestion, I solved this problem
