### ISSUE TITLE
Assertion error when assessing uploaded files, using Ollama and Open WebUI via Docker

### ISSUE THREAD

**Issue by boysbytes** [intel-analytics/ipex-llm#12550]
Hi!

I followed the instructions to [run llama.cpp/Ollama/Open-WebUI on an Intel GPU via Docker](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/DockerGuides/docker_cpp_xpu_quickstart.md). 

I got Ollama serving, Open WebUI running, and Mistral responding to text prompts. Also, I can see that the workload is indeed running on the integrated GPU (13th Gen Core). However, when I upload a file in Open WebUI (or try to use the Knowledge feature) and ask Mistral to summarize the file, I get the following errors:

- In Open WebUI, I get the following notification: _Oops! No text generated from Ollama, Please try again._
- In the Ollama output, I see this error: 
      ```ollama_llama_server: /home/runner/_work/llm.cpp/llm.cpp/llm.cpp/bigdl-core-xe/llama_backend/sdp_xmx_kernel.cpp:439: auto ggml_sycl_op_sdp_xmx_casual(fp16 *, fp16 *, fp16 *, fp16 *, fp16 *, float *, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, float *, float, sycl::queue &)::(anonymous class)::operator()() const: Assertion `false' failed.
SIGABRT: abort
PC=0x7f32cd8429fc m=5 sigcode=18446744073709551610
signal arrived during cgo execution```

Any assistance would be greatly appreciated.

Thanks!

**Comment by sgwhat** [comment]
Hi @boysbytes, which version of ollama are you running? You may see it by `ollama --version`.

**Comment by boysbytes** [comment]
Hello!

Here's the version:
ollama version is 0.4.6-ipexllm-20241214

**Comment by leonardozcm** [comment]
hi @boysbytes, basically I think it is impossible for UHD igpu run into xmx branch, so I wonder if you can provide us more information with the following script
```
// device_check.cpp
#include <CL/sycl.hpp>
#include <iostream>

int main() {
    sycl::device device = sycl::device(sycl::gpu_selector{});

    std::cout << "Device Name: " << device.get_info<sycl::info::device::name>() << std::endl;

    std::cout << "max_num_sub_groups: " << device.get_info<sycl::info::device::max_num_sub_groups>() << std::endl;
    std::cout << "ext_intel_gpu_eu_count: " << device.get_info<sycl::info::device::ext_intel_gpu_eu_count>() << std::endl;
    std::cout << "ext_intel_gpu_eu_simd_width: " << device.get_info<sycl::info::device::ext_intel_gpu_eu_simd_width>() << std::endl;

    std::cout <<std::endl<< "Slice Info:"<<std::endl;
    std::cout << "ext_intel_gpu_slices: " << device.get_info<sycl::info::device::ext_intel_gpu_slices>() << std::endl;
    std::cout << "ext_intel_gpu_subslices_per_slice: " << device.get_info<sycl::info::device::ext_intel_gpu_subslices_per_slice>() << std::endl;
    std::cout << "ext_intel_gpu_eu_count_per_subslice: " << device.get_info<sycl::info::device::ext_intel_gpu_eu_count_per_subslice>() << std::endl;
    std::cout << "Compute Units: " << device.get_info<sycl::info::device::max_compute_units>() << std::endl;
    std::cout << "ext_intel_gpu_hw_threads_per_eu: " << device.get_info<sycl::info::device::ext_intel_gpu_hw_threads_per_eu>() << std::endl;
    std::cout << "Max Work Group Size: " << device.get_info<sycl::info::device::max_work_group_size>() << std::endl;
    std::cout << std::endl;

    std::cout << "preferred_vector_width_char: " << device.get_info<sycl::info::device::preferred_vector_width_char>() << std::endl;
    std::cout << "preferred_vector_width_half: " << device.get_info<sycl::info::device::preferred_vector_width_half>() << std::endl;
    std::cout << "preferred_vector_width_float: " << device.get_info<sycl::info::device::preferred_vector_width_float>() << std::endl;
    std::cout << std::endl;

    std::cout << "Local Memory Type: " << static_cast<int>(device.get_info<sycl::info::device::local_mem_type>()) << std::endl;
    std::cout << "Local Memory Size: " << device.get_info<sycl::info::device::local_mem_size>()/1024 << " Kbytes" << std::endl;
    std::cout << "Global Memory Type: " << static_cast<int>(device.get_info<sycl::info::device::global_mem_cache_type>()) << std::endl;
    std::cout << "Global Memory Size: " << device.get_info<sycl::info::device::global_mem_size>()/1024/1024 << " Mbytes" << std::endl;
    std::cout << "Max Memory Allocation Size: " << device.get_info<sycl::info::device::max_mem_alloc_size>()/1024/1024 << " Mbytes" << std::endl;
    std::cout << "global_mem_cache_size: " << device.get_info<sycl::info::device::global_mem_cache_size>()/1024/1024 << " Mbytes"<< std::endl;
    std::cout << "global_mem_cache_line_size: " << device.get_info<sycl::info::device::global_mem_cache_line_size>() << std::endl;
    std::cout<<"Memory type 0 for none, 1 for local and 2 for global."<<std::endl;
    std::cout << std::endl;



    std::cout<<"Supported subgroup sizes: "<<std::endl;
    for(auto& v: device.get_info<sycl::info::device::sub_group_sizes>()){
        std::cout<<v<<" ";
    }
    std::cout<<std::endl;



    return 0;
}
```

To run this:
```
## source oneapi
source opt/intel/oneapi/setvars.sh

dpcpp device_check.cpp -o device_check
./device_check
```

**Comment by boysbytes** [comment]
Hi @leonardozcm.

Thanks for following up.

Here's the output:
```
Device Name: Intel(R) Graphics [0xa7a8]
max_num_sub_groups: 64
ext_intel_gpu_eu_count: 48
ext_intel_gpu_eu_simd_width: 8

Slice Info:
ext_intel_gpu_slices: 1
ext_intel_gpu_subslices_per_slice: 6
ext_intel_gpu_eu_count_per_subslice: 8
Compute Units: 48
ext_intel_gpu_hw_threads_per_eu: 7
Max Work Group Size: 512

preferred_vector_width_char: 8
preferred_vector_width_half: 4
preferred_vector_width_float: 2

Local Memory Type: 1
Local Memory Size: 64 Kbytes
Global Memory Type: 2
Global Memory Size: 18647 Mbytes
Max Memory Allocation Size: 1024 Mbytes
global_mem_cache_size: 2 Mbytes
global_mem_cache_line_size: 1
Memory type 0 for none, 1 for local and 2 for global.

Supported subgroup sizes:
8 16 32
```

**Comment by leonardozcm** [comment]
hi, I have tried to fix your error. Now it will choose the appropriate calculation method based on device id. Please try latest ipex-llm ollama/llama.cpp **tomorrow**.

And I think there may be something different with your driver or oneapi, for UHD igpu usually displayed as follows:
```
Device Name: Intel(R) UHD Graphics 770
Device ID: a780
max_num_sub_groups: 40
ext_intel_gpu_eu_count: 20
ext_intel_gpu_eu_simd_width: 8
```
Since UHD is not at our mainly supported scope, I suggest you try our product on ARC/Meteor Lake/Lunar Lake etc. for better performance and stability.

**Comment by boysbytes** [comment]
Hi @leonardozcm,

I tried the latest ipex-llm ollama/llama.cpp. The good news is that I can do multiple text prompts. The bad news is that I got gibberish (nonsense response). Because of this, I didn't try uploading a file.

I'm going to drop my experiment to run the workload on the iGPU, and check back on the project again next time.

Thanks for trying to fix my issue. You may close this ticket at your convenience.
