### ISSUE TITLE
Can I select which GPU to run the LLM workload on ipex-llm[cpp]

### ISSUE THREAD

**Issue by jianjungu** [intel-analytics/ipex-llm#12557]
Assume I have a ARL-S + Intel B580, then there are both Intel iGpu and dGpu on my PC. Is there any API or setting so that I can choose which gpu to run the LLM workload?

**Comment by qiuxin2012** [comment]
You can use ONEAPI_DEVICE_SELECTOR, see https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Overview/KeyFeatures/multi_gpus_selection.md#2-oneapi-device-selector.

**Comment by jianjungu** [comment]
can I switch the gpu per request? for example, this request to use iGPU and next request to use dGPU?

**Comment by qiuxin2012** [comment]
> can I switch the gpu per request? for example, this request to use iGPU and next request to use dGPU?

Request? I'm not clear about your question. What service are you using, ollama, llama-server or llama-cli?

**Comment by jianjungu** [comment]
I want to use "ollama serve" to provide a unified LLL infer service to all apps running on windows. But I noticed that different app required different ollama settings, for example: game assistant want to run the infer on iGfx; some app need set OLLAMA_NUM_PARALLEL, OLLAMA_MAX_QUEUE to a large value for multiple infer request simultaneously; some app want to place the model in different path. 

So want I need is to set these paras on the fly without kill the current ollama process and restart it with new paras
