### ISSUE TITLE
main command, libmmd.dll / Svml_dispmd.dl / Sycl7.dll not found when try to run llama

### ISSUE THREAD

**Issue by georgiaWW** [intel-analytics/ipex-llm#12595]
My setup listed below, using windows 11 LNL device with iGPU.
1. create virtual env named:llama-cpp-orig with python 3.11
2. pip install --pre --upgrade ipex-llm[cpp]
3. mkdir llama-cpp & cd llama-cpp
4. use miniforge (installed by miniforge official website installer) with admin then run "init-llama-cpp.bat"
5. set SYCL_CACHE_PERSISTENT=1
rem under most circumstances, the following environment variable may improve performance, but sometimes this may also cause performance degradation
set SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1

Follow this link
https://test-bigdl-llm.readthedocs.io/en/main/doc/LLM/Quickstart/llama3_llamacpp_ollama_quickstart.html
Run llama3
Under your current directory, exceuting below command to do inference with Llama3:
**main -m <model_dir>/Meta-Llama-3-8B-Instruct-Q4_K_M.gguf -n 32 --prompt "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun doing something" -e -ngl 33 --color --no-mmap**

output-
(llama-cpp-orig) (base) C:\Users\Local_Admin\Desktop\llama-cpp>main -m C:\Users\Local_Admin\Desktop\models\Meta-Llama-3-8B-Instruct-Q4_K_M.gguf -n 32 --prompt "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun doing something" -e -ngl 33 --color --no-mmap
_**'main' is not recognized as an internal or external command,
operable program or batch file**_.

Follow this link
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/llama_cpp_quickstart.md
Try to run **llama-cli -m model.gguf -n 32 --prompt "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun" -c 1024 -t 8 -e -ngl 99 --color**

output
![image](https://github.com/user-attachments/assets/9187bb82-c319-4c73-8002-b293857cb3ac)
missing below dlls..
![image](https://github.com/user-attachments/assets/cd7a731b-62d3-42d0-98aa-0fcb170f34cf)

**Comment by qiuxin2012** [comment]
Could you show me your `pip list`?

**Comment by georgiaWW** [comment]
> Could you show me your `pip list`?

(llama-cpp-orig) (base) C:\Users\Local_Admin\Desktop\llama-cpp>pip list
Package                 Version
----------------------- --------------
accelerate              0.33.0
bigdl-core-cpp          2.6.0b20241219
certifi                 2024.12.14
charset-normalizer      3.4.0
colorama                0.4.6
dpcpp-cpp-rt            2024.2.1
filelock                3.16.1
fsspec                  2024.12.0
gguf                    0.13.0
huggingface-hub         0.27.0
idna                    3.10
intel-cmplr-lib-rt      2024.2.1
intel-cmplr-lib-ur      2024.2.1
intel-cmplr-lic-rt      2024.2.1
intel-opencl-rt         2024.2.1
intel-openmp            2024.2.1
intel-sycl-rt           2024.2.1
ipex-llm                2.2.0b20241219
Jinja2                  3.1.4
MarkupSafe              3.0.2
mkl                     2024.2.1
mkl-dpcpp               2024.2.1
mpmath                  1.3.0
networkx                3.4.2
numpy                   1.26.4
onednn                  2024.2.1
onednn-devel            2024.2.1
onemkl-sycl-blas        2024.2.1
onemkl-sycl-datafitting 2024.2.1
onemkl-sycl-dft         2024.2.1
onemkl-sycl-lapack      2024.2.1
onemkl-sycl-rng         2024.2.1
onemkl-sycl-sparse      2024.2.1
onemkl-sycl-stats       2024.2.1
onemkl-sycl-vm          2024.2.1
packaging               24.2
pip                     24.3.1
protobuf                4.25.5
psutil                  6.1.1
PyYAML                  6.0.2
regex                   2024.11.6
requests                2.32.3
safetensors             0.4.6.dev0
sentencepiece           0.1.99
setuptools              65.5.0
sympy                   1.13.3
tbb                     2021.13.1
tokenizers              0.19.1
torch                   2.2.0
tqdm                    4.67.1
transformers            4.44.2
typing_extensions       4.12.2
urllib3                 2.2.3

**Comment by qiuxin2012** [comment]
Your `pip list` looks fine. But please check your python visual env. `(llama-cpp-orig) (base) ` shows you may have two different conda managers?
Here is my result
![image](https://github.com/user-attachments/assets/9b97c2b6-cc17-4eef-bcee-b6bab538ad79)
If I dedactivate my conda env `xin-cpp`, I can get the same missing-dlls error.

**Comment by georgiaWW** [comment]
> Your `pip list` looks fine. But please check your python visual env. `(llama-cpp-orig) (base) ` shows you may have two different conda managers? Here is my result, I have only one `(xin-cpp)` ![image](https://private-user-images.githubusercontent.com/4495653/398084531-9b97c2b6-cc17-4eef-bcee-b6bab538ad79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzk0NDYsIm5iZiI6MTczNDkzOTE0NiwicGF0aCI6Ii80NDk1NjUzLzM5ODA4NDUzMS05Yjk3YzJiNi1jYzE3LTRlZWYtYmNlZS1iNmJhYjUzOGFkNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDczMjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVmNDY3NmQ3MmY2NGVjMjNlZWQxZDc2N2UwZTQ2YjBmOGU5NGI4MDNkYzNjYzg2NzgyOTk4YWY5Y2Q5ZTcwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2S3ebe5hwEhs4rjEcZBRvxsDuqU0LtkrBbwnQSLcLZc) If I dedactivate my conda env `xin-cpp`, I can get the same missing-dlls error.

Actually I can't install conda due to company policy. I use 
![image](https://github.com/user-attachments/assets/7860539e-612c-486a-8de0-6b6cf9596061) to create the virtual env llama-cpp-orig.

Then use miniforge promot to activate it....seems miniforg will have it's (base) then add my env(llama-cpp-orig)
![image](https://github.com/user-attachments/assets/c0cfdd7b-5019-4c0c-957e-b023fc50cb71)

Or change to system prompt and active the virual env, issue still exist.
verified that pip install --pre --upgrade ipex-llm[cpp], all requirement is satisfied.
![image](https://github.com/user-attachments/assets/199d163e-3f85-48c9-8b4d-1350a941fcfd)

Is there any hard requirement to use conda?

**Comment by jason-dai** [comment]
You may use Miniforge instead of conda: https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md#setup-python-environment

**Comment by georgiaWW** [comment]
> You may use Miniforge instead of conda: https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md#setup-python-environment

It seems must use conda/miniforge to handle the virtual env. 
After change to conda and setup again, below command works good.
![image](https://github.com/user-attachments/assets/399e490b-ba44-4574-91d7-e80ad08020cd)



The remaining question is not able to use "main" directly in the env. 
https://test-bigdl-llm.readthedocs.io/en/main/doc/LLM/Quickstart/llama3_llamacpp_ollama_quickstart.html#run-llama3-using-ollama
section 1.3
![image](https://github.com/user-attachments/assets/5850e8b1-f243-4ea4-a4db-9c75ced6ff9f)

This command still not able to perform...
![image](https://github.com/user-attachments/assets/12da64db-4d7f-47ad-8291-cd0bf48fd325)

**Comment by qiuxin2012** [comment]
llama-cli is right commands. The [https://test-bigdl-llm.readthedocs.io](https://test-bigdl-llm.readthedocs.io/en/main/doc/LLM/Quickstart/llama3_llamacpp_ollama_quickstart.html#run-llama3-using-ollama) is deprecated, we will delete them later.

**Comment by georgiaWW** [comment]
It's clear now. Thanks All!
1. Using conda instead of venv. (some binary needs to be handled but not only python)
2. Main command is deprecated. Using llama-cli.
