### ISSUE TITLE
[LNL][llm-npu] Convert model failed

### ISSUE THREAD

**Issue by johnysh** [intel-analytics/ipex-llm#12612]
platform: LNL
OS: win11
NPU driver:  32.0.100.3104
 When convert model , it meets an error as below, but I check model file, it has model_type in config.json
![image](https://github.com/user-attachments/assets/142ced5f-8e29-461e-b46c-93ebff8b07a7)

config.json
![image](https://github.com/user-attachments/assets/4b33474f-1dbb-47cb-833b-3819e39a587d)

pip list
![image](https://github.com/user-attachments/assets/5cc3f047-c6be-4d73-b435-65b1a52abf9d)
![image](https://github.com/user-attachments/assets/f2c2d5e8-e4c2-4b19-a8ca-4e4084615c34)

**Comment by johnysh** [comment]
PS :  model was downloaded from modelscope , not huggface.

**Comment by plusbang** [comment]
Hi, @johnysh ,

As outlined in our documentation(https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/NPU/HF-Transformers-AutoModels/LLM#run), the argument `--save-directory` defines the path to save converted model.

In your case, you specifies `--save-directory` as an existing path, then the low-bit converted model is loaded from the path.

If you only have the original model, please specify `--save-directory` as an non-existing path.

**Comment by johnysh** [comment]
Hi  @plusbang ,   as your suggestion, it can convert success , and output as sample. Further， I want to know how to use convert model?  I use "python ./generate.py  --repo-id-or-path "C:\convert"  " , it alsp reports error  ,can you give me a sample cmd to  use it ?

**Comment by plusbang** [comment]
> Hi @plusbang , as your suggestion, it can convert success , and output as sample. Further， I want to know how to use convert model? I use "python ./generate.py --repo-id-or-path "C:\convert" " , it alsp reports error ,can you give me a sample cmd to use it ?

If you want to use the converted model, please directly specify `--save-directory` as the path to save converted model.

```bash
python llama3.py --save-directory <converted_model_path>
```

**Comment by johnysh** [comment]
Great,  it run successfully.
Thanks!

**Comment by johnysh** [comment]
Can I get the  time  of first token and  rest token？ not the total time ？ I want to use this data to  compare with igpu, thanks!

**Comment by plusbang** [comment]
> Can I get the time of first token and rest token？ not the total time ？ I want to use this data to compare with igpu, thanks!

We also provide all-in-one benchmark scripts for NPU, please specify test-api as `- "transformers_int4_npu_win"` here (https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/dev/benchmark/all-in-one/config.yaml#L38).

**Comment by johnysh** [comment]
@plusbang ， hello
  I ran  run.py and it didn't report any error , but couldn't find result.csv file 
![image](https://github.com/user-attachments/assets/1bd43d89-509c-4e64-8c44-03e815ab16da)

config.yaml as below:
![image](https://github.com/user-attachments/assets/f347ab38-03a1-41a2-944f-ab45fe8ee6c3)

**Comment by plusbang** [comment]
> 
> config.yaml as below: ![image](https://private-user-images.githubusercontent.com/15604431/398648614-f347ab38-03a1-41a2-944f-ab45fe8ee6c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDQ1OTQsIm5iZiI6MTczNTIwNDI5NCwicGF0aCI6Ii8xNTYwNDQzMS8zOTg2NDg2MTQtZjM0N2FiMzgtMDNhMS00MWEyLTk0NGYtYWI0NWZlOGVlNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZWY1MWViZDFiMzU5NTVkOGRmMDk2NzgyOTUzZjQ3NzhmNWY0ZDkwZmRmOGUzMDRkYzA2MDkxYmJjZmM5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fGVxeRzpo8qBQvc2a4AX8wPzUmbvCLzyS2OAYqMKSHk)

Please just specify a single in_out_pair.

**Comment by johnysh** [comment]
@plusbang  ,  I can't see this image. ^^!  
![image](https://github.com/user-attachments/assets/e520d5f4-fa7b-40d0-94c7-14b0b8a20b50)

**Comment by plusbang** [comment]
> @plusbang , I can't see this image. ^^!

This image directly quotes your response, maybe we could ignore it : )

**Comment by johnysh** [comment]
@plusbang   Thanks binbin ,  it can be closed !

**Comment by Martin-HZK** [comment]
I have no idea what is the difference between the convert.py in the CPP_Examples directory and the qwen.py , llama2.py, llama3.py?

**Comment by plusbang** [comment]
> I have no idea what is the difference between the convert.py in the CPP_Examples directory and the qwen.py , llama2.py, llama3.py etc.? [@plusbang](https://github.com/plusbang)

The conversion logic remains the same, and provide model specific example for demonstration.
