### ISSUE TITLE
FastChat serving demo validation based on CoCo

### ISSUE THREAD

**Issue by holmastoo** [intel-analytics/ipex-llm#8823]
Hi, I want to deploy Trusted-LLM serving demo on Confidential Containers, but there is no guide and RA API may be different, any ideas?

**Comment by gc-fu** [comment]
A `README.md` file for how to boot the service in Kubernetes environment has been validated in both `naitve` and `TDX-CoCo` cluster.

For remote attestation, we have just finished the RA API development, a `README.md` on how to use the RA API will be provided later.
