### ISSUE TITLE
it is too slower for LLM inference with beam=2 on ARC770

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#9321]
the speed is 5.x slower with beam searching than greedy mode, does BigDL-LLM not optimize for beam searching mode?

**Comment by MeouSker77** [comment]
Could you tell us which model are you running so that we can reproduce this?

**Comment by MeouSker77** [comment]
Could you try the latest `bigdl-llm[xpu]==2.4.0b20231101` ? It should fix this problem.

**Comment by hkvision** [comment]
@Fred-cell Any update on this issue? Does the current speed satisfy your needs?
