### ISSUE TITLE
Need release a stable version for LLM as soon as possible

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#9516]
now the stability of BigDL-LLM has some problem, there is not a stable version to deploy online now, could you release a stable version for RPC region which includes chatGLM2/3-6b, llama2-7b, baichuan1/2-7b and qianwen-7b?

**Comment by hkvision** [comment]
We will do stress test for a stable version after https://github.com/intel-analytics/BigDL/issues/9429 and https://github.com/intel-analytics/BigDL/issues/9408 are fixed.
