### ISSUE TITLE
Does BigDL-LLM support Windows OS on Arc?

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#9517]
there is no windows version now for pip installation.

**Comment by 0xDEADFED5** [comment]
i've been keeping an eye on this.  i assume you're referring to https://github.com/intel-analytics/BigDL-core for Windows?  any chance you would be willing to add the Windows code on a separate branch for testing purposes?  i saw the partial Windows support in the code, but I suck at Maven

**Comment by 0xDEADFED5** [comment]
any chance the Windows code could be placed in a separate branch for testing?  i was attempting to get it going, but ran into BigDL-core having only partial Windows support, and I suck at Maven

**Comment by hkvision** [comment]
Which module in BigDL are you using to run on Windows?

**Comment by hkvision** [comment]
> For running on GPU, we have internally build a windows build version, and the public version is work in progress. For running on CPU, it is already supported and you can directly install it with pip.

Now for BigDL-LLM, we have already supported Windows on GPU, see more details and steps here: https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html

**Comment by openvino-book** [comment]
> there is no windows version now for pip installation.

@Fred-cell [三步完成在英特尔独立显卡上量化和部署 ChatGLM3-6B 模型](https://mp.weixin.qq.com/s/uLQHPc9dhQaCaG1KXB8z5Q)
