### ISSUE TITLE
chat with chatglm3-6b and baichuan2-7b-chat is too slow

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#9526]
安装的时1122的版本，做chat聊天测试，脚本如下：
python streamchat.py --repo-id-or-model-path ~/workspace/pretrained-model/chatglm3-6b/ --question "介绍一下北京"
速度非常慢。

**Comment by hkvision** [comment]
@sgwhat Please check this.

**Comment by sgwhat** [comment]
Both `ipex fp16` and `sym_int4` are experiencing the same issue. Upon observing GPU usage, there is no increase in GPU Memory Used. It seems to be a machine-related problem.

**Comment by hkvision** [comment]
Doubt if this issue is caused by linux kernel 6.2, Fred is downgrading to 5.19 and re-check this.

**Comment by hkvision** [comment]
Confirmed this is due to the fan is not working and Arc is in abnormal temperature. Fred will retest it when the machine gets back to normal.
