### ISSUE TITLE
baichuan2-7b inference with fp8 and 2k prompt input hung after 1st iterator

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#9803]
bigdl-llm[xpu_2.1]=1226, fp8, error is as below:
2023-12-28 10:45:58,065 - bigdl.llm.transformers.utils - INFO - Converting the current model to fp8_e4m3 format......
2023-12-28 10:46:11,837 - bigdl.llm.transformers.models.baichuan2 - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
<class 'transformers_modules.modeling_baichuan.BaichuanForCausalLM'>
=========First token cost 7.7901 s=========
=========Rest tokens cost average 0.0306 s (511 tokens in all)=========
cpu utilization is 0%:
Timestamp, DeviceId, GPU Utilization (%), GPU Memory Utilization (%), GPU Memory Bandwidth Utilization (%), GPU Memory Used (MiB)
10:51:49.000,    0, 0.00, 94.86,  N/A, 15451.09
10:51:50.000,    0, 0.00, 94.86,  N/A, 15451.09
10:51:51.000,    0, 0.00, 94.86,  N/A, 15451.09
10:51:52.000,    0, 0.00, 94.86,  N/A, 15451.09

**Comment by hkvision** [comment]
For baichuan2-7b on arc, 2k-256 is successful and 2k-512 is OOM.

**Comment by Fred-cell** [comment]
when I installed 2025.0.b1 and the error is the same as before:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/7d5809c4-51d5-49d2-a3b7-9cfaf4e62068)
![image](https://github.com/intel-analytics/BigDL/assets/99886928/1559730d-a92c-4e8c-8831-a0ac88a4ff94)

**Comment by hkvision** [comment]
> For baichuan2-7b on arc, 2k-256 is successful and 2k-512 is OOM. We will work on the memory optimization.

This is unknown issue and we are not targeted to improve the memory usage in 2.5.0b1 since it is still work in progress. Will notify you when we successfully improve this.

**Comment by lalalapotter** [comment]
Can run normally in latest version, close issue.
