### ISSUE TITLE
Facing vulnerability issue with pyspark and ray version using bigdl-spark3==2.4.0

### ISSUE THREAD

**Issue by SjeYinTeoIntel** [intel-analytics/ipex-llm#9903]
Below result is from trivy scan where pyspark==3.1.3 and ray==2.6.3 having vulnerability issue.
![image](https://github.com/intel-analytics/BigDL/assets/78522263/53f204ca-a93b-45e2-b2ce-a3bfe1190266)

I'm trying to upgrade pyspark to 3.2.2 version but it will incompatible with bigdl-dllib-spark3 2.4.0.
![image](https://github.com/intel-analytics/BigDL/assets/78522263/8625e800-5078-488f-9153-3c432475c3c2)

when trying to upgrade ray to latest version, bigdl-nano 2.4.0 requires protobuf==3.19.5 where only compatible to ray==2.6.3.
![image](https://github.com/intel-analytics/BigDL/assets/78522263/0ed46dfd-ff15-4bb1-8df1-f0df7094a00d)

Is there a new release that using updated pyspark & ray library?

**Comment by sgwhat** [comment]
Hi @SjeYinTeoIntel, we do not have a release that supports the latest versions of Spark and Ray. Installing BigDL will automatically install the required corresponding versions of dependencies.
